const $=s=>document.querySelector(s), root=$('#viewRoot');let store={products:[],orders:[],customers:[],leads:[]},current='dashboard';
const money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), cls=v=>String(v??'').replace(/[^A-Za-z]/g,'');
async function api(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function refresh(){const [products,orders,customers,leads]=await Promise.all(['/api/products','/api/crm/orders','/api/crm/customers','/api/crm/leads'].map(u=>api(u)));store={products,orders,customers,leads};$('#orderBadge').textContent=orders.length}
async function load(){try{await refresh();show('dashboard')}catch(err){root.innerHTML=`${title('Dashboard')}<div class="empty-state">Could not load CRM data. Is the backend running? (${esc(err.message)})</div>`}}
function title(name,sub='EA LUXURY ITALIAN BRANDS'){return `<div class="page-title"><div><h1>${name}</h1><p>${sub}</p></div><div class="date-chip">${new Date().toLocaleDateString('en-GB',{month:'short',year:'numeric'}).toUpperCase()}</div></div>`}
function dashboard(){const revenue=store.orders.reduce((a,b)=>a+b.total,0);const low=store.products.filter(p=>p.stock<6);const brandTotals={};store.products.forEach(p=>brandTotals[p.brand]=(brandTotals[p.brand]||0)+p.price);const max=Math.max(...Object.values(brandTotals));return `${title('Dashboard','WELCOME TO EA LUXURY ITALIAN BRANDS')}<div class="cards"><div class="metric"><label>TOTAL REVENUE</label><strong>${money(revenue)}</strong><span>↑ Current orders</span></div><div class="metric"><label>CUSTOMERS</label><strong>${store.customers.length}</strong><span>CRM contacts</span></div><div class="metric"><label>ACTIVE ORDERS</label><strong>${store.orders.filter(o=>o.status!=='Delivered').length}</strong><span>Awaiting fulfilment</span></div><div class="metric"><label>LOW-STOCK ITEMS</label><strong>${low.length}</strong><span class="low-stock">Needs attention</span></div></div><div class="dashboard-grid"><div class="panel"><h3>REVENUE OVER TIME</h3><div class="line-chart">${[24,34,29,52,44,63,58,78,66,91].map((h,i)=>`<div class="bar" style="height:${h}%" data-label="${i+1}"></div>`).join('')}</div></div><div class="panel"><h3>SALES BY BRAND</h3>${Object.entries(brandTotals).map(([b,v])=>`<div class="brand-stat"><span>${esc(b)}</span><div class="track"><div class="fill" style="width:${Math.round(v/max*100)}%"></div></div><b>${Math.round(v/max*100)}%</b></div>`).join('')}</div><div class="panel"><h3>CUSTOMER ACTIVITY</h3><div class="activity">${[48,62,35,75,56,83,68,92,61,78].map(h=>`<span style="height:${h}%"></span>`).join('')}</div></div></div>${ordersTable(true)}<div class="table-panel"><div class="table-head"><h3>LOW STOCK ALERTS</h3></div><table class="data-table"><tbody>${low.map(p=>`<tr><td><img class="thumb" src="${esc(p.image)}" alt=""></td><td>${esc(p.name)}<br><small>${esc(p.brand)}</small></td><td class="low-stock">${p.stock} in stock</td></tr>`).join('')||'<tr><td>All products are well stocked.</td></tr>'}</tbody></table></div>`}
function ordersTable(compact=false){const rows=compact?store.orders.slice(0,5):store.orders;return `<div class="table-panel"><div class="table-head"><h3>${compact?'RECENT ORDERS':'ORDERS'}</h3>${compact?'<button data-view="orders">View all →</button>':'<button class="primary" id="newOrder">New order</button>'}</div><table class="data-table"><thead><tr><th>#</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${o.items}</td><td>${money(o.total)}</td><td><span class="status ${cls(o.status)}">${esc(o.status)}</span></td><td>${esc(o.date)}</td></tr>`).join('')}</tbody></table></div>`}
function customers(){return `${title('Customers')}<div class="table-panel"><div class="table-head"><h3>CUSTOMER DIRECTORY</h3><button id="newCustomer">Add customer</button></div><table class="data-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>City</th><th>Orders</th><th>Lifetime spend</th><th>Status</th></tr></thead><tbody>${store.customers.map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.name)}</td><td>${esc(c.email)}</td><td>${esc(c.city)}</td><td>${c.orders}</td><td>${money(c.spent)}</td><td><span class="status ${cls(c.status)}">${esc(c.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
function products(){return `${title('Products')}<div class="products-grid">${store.products.map(p=>`<article class="product-admin"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div class="meta"><small>${esc(p.brand)}</small><h4>${esc(p.name)}</h4><p>${money(p.price)} · Stock ${p.stock}</p></div></article>`).join('')}</div>`}
function inventory(){return `${title('Inventory')}<div class="table-panel"><div class="table-head"><h3>STOCK CONTROL</h3></div><table class="data-table"><thead><tr><th>Item</th><th>Brand</th><th>Category</th><th>Price</th><th>Stock</th></tr></thead><tbody>${store.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.brand)}</td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td class="${p.stock<6?'low-stock':''}">${p.stock}</td></tr>`).join('')}</tbody></table></div>`}
function leads(){return `${title('Leads')}<div class="table-panel"><div class="table-head"><h3>LEAD PIPELINE</h3><button id="newLead">Add lead</button></div><table class="data-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Source</th><th>Stage</th></tr></thead><tbody>${store.leads.map(l=>`<tr><td>${esc(l.id)}</td><td>${esc(l.name)}</td><td>${esc(l.email)}</td><td>${esc(l.source)}</td><td><span class="status ${cls(l.stage)}">${esc(l.stage)}</span></td></tr>`).join('')}</tbody></table></div>`}
function show(view){current=view;$('#globalSearch').value='';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));root.innerHTML=view==='dashboard'?dashboard():view==='orders'?title('Orders')+ordersTable():view==='customers'?customers():view==='products'?products():view==='inventory'?inventory():leads();bindView()}
function openModal(html){$('#modalBody').innerHTML=html;$('#modal').classList.add('open');$('#modalBody input, #modalBody select')?.focus()}function closeModal(){$('#modal').classList.remove('open')}
const formError='<p class="form-error" role="alert"></p>';
const forms={
 orderForm:{url:'/api/crm/orders',view:'orders',html:()=>`<h2>New order</h2><form id="orderForm"><label>Customer</label><select name="customerId" required>${store.customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${esc(c.email)}</option>`).join('')}</select><label>Items</label><input name="items" type="number" min="1" max="99" step="1" value="1" required><label>Total (€)</label><input name="total" type="number" min="1" step="1" required><label>Status</label><select name="status"><option>Processing</option><option>Shipped</option><option>Delivered</option></select>${formError}<button>Create order</button></form>`},
 customerForm:{url:'/api/crm/customers',view:'customers',html:()=>`<h2>Add customer</h2><form id="customerForm"><label>Name</label><input name="name" required maxlength="120"><label>Email</label><input name="email" type="email" required><label>City</label><input name="city" maxlength="80">${formError}<button>Save customer</button></form>`},
 leadForm:{url:'/api/crm/leads',view:'leads',html:()=>`<h2>Add lead</h2><form id="leadForm"><label>Name</label><input name="name" required maxlength="120"><label>Email</label><input name="email" type="email" required><label>Source</label><input name="source" value="Website" maxlength="60">${formError}<button>Save lead</button></form>`},
};
function bindView(){root.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#newOrder')?.addEventListener('click',()=>openModal(forms.orderForm.html()));$('#newCustomer')?.addEventListener('click',()=>openModal(forms.customerForm.html()));$('#newLead')?.addEventListener('click',()=>openModal(forms.leadForm.html()))}
// Forms are created when the modal opens, so submits are handled by delegation on the modal body.
$('#modalBody').addEventListener('submit',async e=>{const form=forms[e.target.id];if(!form)return;e.preventDefault();const btn=e.target.querySelector('button'),error=e.target.querySelector('.form-error');btn.disabled=true;error.textContent='';try{await post(form.url,Object.fromEntries(new FormData(e.target)));await refresh();closeModal();show(form.view)}catch(err){error.textContent=err.message}finally{btn.disabled=false}});
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#modalClose').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){show(current);return}document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));const hits=[...store.customers.map(x=>({type:'Customer',name:x.name,detail:x.email})),...store.leads.map(x=>({type:'Lead',name:x.name,detail:x.email})),...store.orders.map(x=>({type:'Order',name:x.id,detail:x.customer})),...store.products.map(x=>({type:'Product',name:x.name,detail:x.brand}))].filter(x=>`${x.name} ${x.detail}`.toLowerCase().includes(q));root.innerHTML=`${title('Search')}<div class="table-panel"><table class="data-table"><tbody>${hits.map(h=>`<tr><td>${h.type}</td><td>${esc(h.name)}</td><td>${esc(h.detail)}</td></tr>`).join('')||'<tr><td>No results</td></tr>'}</tbody></table></div>`});
load();
