const $=s=>document.querySelector(s), root=$('#viewRoot');let store={products:[],orders:[],customers:[],leads:[]},current='dashboard';
const money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), cls=v=>String(v??'').replace(/[^A-Za-z]/g,'');
// A signed-out session (expired, or signed out in another tab) goes back to the sign-in page.
async function api(url,opts){const r=await fetch(url,opts);if(r.status===401){location.replace('/admin/login.html');throw new Error('Please sign in again.')}const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const put=(url,body)=>api(url,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function refresh(){const [products,orders,customers,leads]=await Promise.all(['/api/crm/products','/api/crm/orders','/api/crm/customers','/api/crm/leads'].map(u=>api(u)));store={products,orders,customers,leads};syncBadges()}
// What needs doing: orders still to ship (sidebar badge) plus products low on stock (bell).
const LOW=6, lowStock=()=>store.products.filter(p=>p.stock<LOW);
function syncBadges(){const toShip=store.orders.filter(o=>o.status==='Processing').length,low=lowStock().length,alerts=toShip+low;$('#orderBadge').textContent=toShip;$('#orderBadge').hidden=!toShip;$('#alertCount').textContent=alerts;$('#alertCount').hidden=!alerts;$('#alertsBtn').setAttribute('aria-label',alerts?`Needs attention: ${toShip} to ship, ${low} low on stock`:'Nothing needs attention')}
async function load(){root.innerHTML='<p class="loading">Loading the CRM…</p>';try{const me=await api('/api/auth/me');$('#userName').textContent=me.username;$('#avatar').textContent=me.username.slice(0,2).toUpperCase();await refresh();show('dashboard')}catch(err){root.innerHTML=`${title('Dashboard')}<div class="empty-state"><p>The CRM data could not be loaded. ${esc(err.message)}</p><button class="primary" id="retryLoad">Try again</button></div>`;$('#retryLoad').addEventListener('click',load)}}
let toastTimer;function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.classList.toggle('error',error);t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3200)}
function title(name,sub='EA LUXURY ITALIAN BRANDS'){return `<div class="page-title"><div><h1>${name}</h1><p>${sub}</p></div><div class="date-chip">${new Date().toLocaleDateString('en-GB',{month:'short',year:'numeric'}).toUpperCase()}</div></div>`}
// Dashboard: every number comes from the orders, customers and products; cards and rows open what they summarise.
const sum=(list,f)=>list.reduce((n,x)=>n+f(x),0), dayKey=d=>d.toLocaleDateString('en-CA'), plural=(n,one,many=`${one}s`)=>`${n} ${n===1?one:many}`;
function dashboard(){const o=store.orders,revenue=sum(o,x=>x.total),low=lowStock(),soldOut=store.products.filter(p=>!p.stock).length,count=s=>o.filter(x=>x.status===s).length;
const card=(attrs,label,value,sub,warn=false)=>`<button class="metric" ${attrs}><span class="metric-label">${label}</span><strong>${value}</strong><span class="metric-sub${warn?' low-stock':''}">${sub}</span></button>`;
return `${title('Dashboard','WELCOME TO EA LUXURY ITALIAN BRANDS')}<div class="cards">${card('data-view="orders" data-order-filter="All"','Total revenue',money(revenue),o.length?`${plural(o.length,'order')} · avg ${money(revenue/o.length)}`:'No orders yet')}${card('data-view="customers"','Customers',store.customers.length,`${store.customers.filter(c=>c.status==='VIP').length} VIP · ${store.customers.filter(c=>c.status==='New').length} new`)}${card('data-view="orders" data-order-filter="Processing"','Active orders',o.length-count('Delivered'),`${count('Processing')} to ship · ${count('Shipped')} in transit`)}${card('data-view="inventory" data-stock-filter="Low stock"','Low-stock items',low.length,low.length?`${soldOut} sold out · needs attention`:'All well stocked',low.length>0)}</div>
<div class="dashboard-grid">${revenuePanel()}${brandPanel()}${customerPanel()}</div>${ordersTable(true)}<div class="table-panel" id="lowStock"><div class="table-head"><h3>LOW STOCK ALERTS</h3>${low.length?'<button data-view="inventory" data-stock-filter="Low stock">Inventory →</button>':''}</div><table class="data-table"><tbody>${low.map(p=>`<tr class="clickable" data-edit-row="${esc(p.id)}" title="Edit product"><td><img class="thumb" src="${esc(p.image)}" alt=""></td><td>${esc(p.name)}<br><small>${esc(p.brand)}</small></td><td class="low-stock">${p.stock?`${p.stock} in stock`:'Sold out'}</td><td>${outSizes(p)}</td></tr>`).join('')||'<tr><td>All products are well stocked.</td></tr>'}</tbody></table></div>`}
const outSizes=p=>{const out=(p.sizes||[]).filter(s=>!s.qty).map(s=>esc(s.size));return out.length?`<small>Sold out in ${out.join(', ')}</small>`:''};
// Revenue for each of the last 14 days.
function revenuePanel(){const days=[...Array(14)].map((_,i)=>{const d=new Date();d.setDate(d.getDate()-13+i);return d}),byDay={};store.orders.forEach(x=>byDay[x.date]=(byDay[x.date]||0)+x.total);const vals=days.map(d=>byDay[dayKey(d)]||0),max=Math.max(...vals,1),total=sum(vals,v=>v);
return `<div class="panel"><div class="panel-head"><h3>REVENUE · LAST 14 DAYS</h3><b>${money(total)}</b></div><div class="line-chart" role="img" aria-label="Revenue per day over the last 14 days, ${money(total)} in total">${days.map((d,i)=>`<div class="bar${vals[i]?'':' zero'}" style="height:${vals[i]?Math.max(vals[i]/max*100,4):1}%" data-label="${d.getDate()}" title="${d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}: ${money(vals[i])}"></div>`).join('')}</div></div>`}
// Sales by brand from the pieces in store orders; until there are any, the stock value held per brand.
function brandPanel(){const lines=store.orders.flatMap(x=>x.lines||[]),sales=lines.length>0,totals={};if(sales)lines.forEach(l=>totals[l.brand]=(totals[l.brand]||0)+l.price*l.qty);else store.products.forEach(p=>totals[p.brand]=(totals[p.brand]||0)+p.price*p.stock);const rows=Object.entries(totals).sort((a,b)=>b[1]-a[1]),max=Math.max(...rows.map(r=>r[1]),1);
return `<div class="panel"><div class="panel-head"><h3>${sales?'SALES BY BRAND':'STOCK VALUE BY BRAND'}</h3></div>${rows.map(([b,v])=>`<div class="brand-stat"><span>${esc(b)}</span><div class="track"><div class="fill" style="width:${Math.round(v/max*100)}%"></div></div><b>${money(v)}</b></div>`).join('')||'<p class="media-empty">No products yet.</p>'}${sales?'':'<p class="panel-note">Sales by brand appear here once the store takes orders.</p>'}</div>`}
// The customers who have spent the most.
function customerPanel(){const top=[...store.customers].sort((a,b)=>b.spent-a.spent).slice(0,5),max=Math.max(...top.map(c=>c.spent),1);
return `<div class="panel"><div class="panel-head"><h3>TOP CUSTOMERS</h3><button class="link-btn" data-view="customers">All →</button></div>${top.map(c=>`<div class="brand-stat customer-stat"><span>${esc(c.name)}<small>${plural(c.orders,'order')}</small></span><div class="track"><div class="fill" style="width:${Math.round(c.spent/max*100)}%"></div></div><b>${money(c.spent)}</b></div>`).join('')||'<p class="media-empty">No customers yet.</p>'}</div>`}
// Orders: filter by status, and change an order's status right in the table (or in its details).
const ORDER_STATUSES=['Processing','Shipped','Delivered'];let orderFilter='All';
const statusSelect=o=>`<select class="status-select ${cls(o.status)}" data-status="${esc(o.id)}" aria-label="Status of order ${esc(o.id)}">${ORDER_STATUSES.map(s=>`<option${s===o.status?' selected':''}>${s}</option>`).join('')}</select>`;
const chips=(attr,options,cur,countOf)=>`<div class="chips" role="group">${options.map(s=>`<button class="chip" ${attr}="${s}" aria-pressed="${s===cur}">${s} <span>${countOf(s)}</span></button>`).join('')}</div>`;
function ordersTable(compact=false){const all=store.orders,rows=compact?all.slice(0,5):all.filter(o=>orderFilter==='All'||o.status===orderFilter);
return `<div class="table-panel"><div class="table-head"><h3>${compact?'RECENT ORDERS':'ORDERS'}</h3>${compact?'<button data-view="orders" data-order-filter="All">View all →</button>':'<button class="primary" id="newOrder">New order</button>'}</div>${compact?'':chips('data-order-filter',['All',...ORDER_STATUSES],orderFilter,s=>s==='All'?all.length:all.filter(o=>o.status===s).length)}<table class="data-table"><thead><tr><th>#</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map(o=>`<tr class="clickable" data-order="${esc(o.id)}" title="Show order details"><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${o.items}</td><td>${money(o.total)}</td><td>${statusSelect(o)}</td><td>${esc(o.date)}</td></tr>`).join('')||`<tr><td colspan="6" class="empty-row">No ${orderFilter==='All'?'':orderFilter.toLowerCase()+' '}orders.</td></tr>`}</tbody></table></div>`}
// Order details: what to ship and where. Orders placed at the store's checkout carry the contact, address and pieces.
function orderDetails(o){const a=o.address,fact=(label,html)=>html?`<div><label>${label}</label><p>${html}</p></div>`:'';
return `<h2>Order ${esc(o.id)}</h2><div class="order-facts">${fact('Customer',[o.customer,o.email,o.phone].filter(Boolean).map(esc).join('<br>'))}${fact('Ship to',a&&[a.line1,a.line2,`${a.postalCode} ${a.city}`,a.country].filter(Boolean).map(esc).join('<br>'))}${fact('Status',`${statusSelect(o)} <span class="fact-meta">${esc(o.date)}${o.source?` · ${esc(o.source)}`:''}</span>`)}${fact('Delivery',esc(o.delivery))}${fact('Payment',esc(o.payment))}${fact('Note',esc(o.note))}</div>
${o.lines?`<table class="data-table order-lines"><thead><tr><th></th><th>Piece</th><th>Colour</th><th>Size</th><th>Qty</th><th>Price</th></tr></thead><tbody>${o.lines.map(l=>`<tr><td><img class="thumb" src="${esc(l.image)}" alt=""></td><td>${esc(l.name)}<br><small>${esc(l.brand)}</small></td><td>${esc(l.color||'–')}</td><td>${esc(l.size||'–')}</td><td>${l.qty}</td><td>${money(l.price*l.qty)}</td></tr>`).join('')}</tbody></table>`:`<p class="media-empty">${o.items} ${o.items===1?'item':'items'}; this order was entered in the CRM, without piece details.</p>`}
<dl class="order-totals">${o.lines?`<dt>Subtotal</dt><dd>${money(o.subtotal)}</dd><dt>Delivery</dt><dd>${o.shipping?money(o.shipping):'Free'}</dd>`:''}<dt>Total</dt><dd>${money(o.total)}</dd></dl>`}
function customers(){return `${title('Customers')}<div class="table-panel"><div class="table-head"><h3>CUSTOMER DIRECTORY</h3><button id="newCustomer">Add customer</button></div><table class="data-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>City</th><th>Orders</th><th>Lifetime spend</th><th>Status</th></tr></thead><tbody>${[...store.customers].sort((a,b)=>b.spent-a.spent).map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.name)}</td><td><a class="mail" href="mailto:${esc(c.email)}">${esc(c.email)}</a></td><td>${esc(c.city)}</td><td>${c.orders}</td><td>${money(c.spent)}</td><td><span class="status ${cls(c.status)}">${esc(c.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
const brandList=()=>[...new Set(store.products.map(p=>p.brand))].sort((a,b)=>a.localeCompare(b));
let productBrand='All'; // Products page brand filter
// Products: search, filter and sort the catalogue; a one-size piece's stock can be changed right on its card.
let productQuery='',productSort='new',productFilter='All';
const PRODUCT_FILTERS={All:()=>true,'Low stock':p=>p.stock<LOW,'On sale':p=>p.discount>0,Hidden:p=>!!p.hidden};
const PRODUCT_SORTS={new:['Newest first',(a,b)=>store.products.indexOf(b)-store.products.indexOf(a)],name:['Name A–Z',(a,b)=>a.name.localeCompare(b.name)],priceUp:['Price: low to high',(a,b)=>priceOf(a)-priceOf(b)],priceDown:['Price: high to low',(a,b)=>priceOf(b)-priceOf(a)],stock:['Stock: lowest first',(a,b)=>a.stock-b.stock]};
function productRows(){const words=productQuery.toLowerCase().split(/\s+/).filter(Boolean);return store.products.filter(p=>(productBrand==='All'||p.brand===productBrand)&&PRODUCT_FILTERS[productFilter](p)&&words.every(w=>`${p.name} ${p.brand} ${p.type||''} ${p.code||''}`.toLowerCase().includes(w))).sort(PRODUCT_SORTS[productSort][1])}
const stockLine=p=>p.sizes?.length?`<p class="stock-sizes">${p.sizes.map(s=>`<span class="${s.qty?'':'low-stock'}">${esc(s.size)} ${s.qty}</span>`).join('')}</p>`:`<label class="stock-edit">Stock <input type="number" min="0" step="1" value="${p.stock}" data-stock="${esc(p.id)}" aria-label="Stock of ${esc(p.name)}"></label>`;
const adminCard=p=>`<article class="product-admin${p.hidden?' is-hidden':''}" data-edit="${esc(p.id)}"><img src="${esc(p.image)}" alt="${esc(p.name)}" loading="lazy"><div class="meta"><small>${esc(p.brand)}${p.type?` · ${esc(p.type)}`:''}</small>${p.hidden?'<b class="tag hidden-tag">Hidden</b>':''}${p.isNew?'<b class="tag">New arrival</b>':''}${p.discount?`<b class="tag sale">−${p.discount}%</b>`:''}<h4>${esc(p.name)}</h4><p>${p.discount?`<s>${money(p.price)}</s> ${money(priceOf(p))}`:money(p.price)} · ${(p.media||[]).length>1?`${p.media.length} photos/videos`:'1 photo'}</p>${stockLine(p)}<button class="edit-link">Edit</button></div></article>`;
const productCardsHtml=()=>productRows().map(adminCard).join('')||'<p class="empty-row">No products match. Clear the search or the filters.</p>';
function products(){const brands=brandList();if(!brands.includes(productBrand))productBrand='All';const count=b=>store.products.filter(p=>p.brand===b).length;
return `${title('Products')}<div class="table-panel"><div class="table-head"><h3>PRODUCT CATALOGUE</h3><button class="primary" id="newProduct">Add product</button></div><div class="product-tools"><div class="tool-search"><svg aria-hidden="true"><use href="#i-search"/></svg><label class="vh" for="productSearch">Search products</label><input id="productSearch" type="search" placeholder="Search name, brand, type or code" value="${esc(productQuery)}" autocomplete="off"></div><select id="brandFilter" aria-label="Brand"><option value="All">All brands (${store.products.length})</option>${brands.map(b=>`<option value="${esc(b)}"${b===productBrand?' selected':''}>${esc(b)} (${count(b)})</option>`).join('')}</select><select id="productSort" aria-label="Sort by">${Object.entries(PRODUCT_SORTS).map(([k,[label]])=>`<option value="${k}"${k===productSort?' selected':''}>${label}</option>`).join('')}</select></div>${chips('data-product-filter',Object.keys(PRODUCT_FILTERS),productFilter,f=>store.products.filter(PRODUCT_FILTERS[f]).length)}</div><div class="products-grid" id="productGrid">${productCardsHtml()}</div>`}
// Inventory: all pieces, or only those low on stock / sold out; a row opens the product editor.
const STOCK_FILTERS={All:()=>true,'Low stock':p=>p.stock<LOW,'Sold out':p=>!p.stock};let stockFilter='All';
function inventory(){const rows=store.products.filter(STOCK_FILTERS[stockFilter]);return `${title('Inventory')}<div class="table-panel"><div class="table-head"><h3>STOCK CONTROL</h3><span class="head-note">${money(sum(store.products,p=>priceOf(p)*p.stock))} in stock at current prices</span></div>${chips('data-stock-filter',Object.keys(STOCK_FILTERS),stockFilter,s=>store.products.filter(STOCK_FILTERS[s]).length)}<table class="data-table"><thead><tr><th>Item</th><th>Brand</th><th>Gender</th><th>Type</th><th>Price</th><th>Stock</th><th>Stock per size</th></tr></thead><tbody>${rows.length?'':`<tr><td colspan="7" class="empty-row">No ${stockFilter.toLowerCase()} pieces.</td></tr>`}${rows.map(p=>`<tr class="clickable" data-edit-row="${esc(p.id)}" title="Edit product"><td>${esc(p.name)}</td><td>${esc(p.brand)}</td><td>${esc(p.category)}</td><td>${esc(p.type)}</td><td>${money(p.price)}</td><td class="${p.stock<6?'low-stock':''}">${p.stock}</td><td>${(p.sizes||[]).map(s=>`<span class="${s.qty?'':'low-stock'}">${esc(s.size)}: ${s.qty}</span>`).join(' · ')||'One size'}</td></tr>`).join('')}</tbody></table></div>`}
// Product editor: a full page with every piece of the store's product page (photos, sizes, colours, Info & Details, care),
// a live preview of the store card, visibility, and a save bar that tracks unsaved changes (Ctrl+S saves).
// Gender is saved as the product's `category`, which the store's Women / Men / Kids pages filter on.
const CAT=window.EA_CATALOG, GENDERS=['Women','Men','Unisex','Kids'], MB=1024*1024, UPLOAD_LIMITS={image:15*MB,video:95*MB}, NEW_BRAND='__new';
let draft=null; // product being edited: {id, media:[{type,src} | {uploading,id,name,progress}]}
// Type dropdown, grouped by what the product is (Clothing, Shoes, …). A product's older type that isn't listed is kept as an option.
function typeOptions(cur){const group=CAT.typeGroup(cur);return `${cur?'':'<option value="" selected disabled>Choose a type</option>'}${cur&&!group?`<option selected>${esc(cur)}</option>`:''}${Object.entries(CAT.types).map(([g,list])=>`<optgroup label="${g}">${(g===group&&!list.includes(cur)?[cur,...list]:list).map(t=>`<option${t===cur?' selected':''}>${esc(t)}</option>`).join('')}</optgroup>`).join('')}`}
let editorProduct=null,editorSnapshot=null,editorForceDirty=false;
const LEAVE='Leave this product without saving? Your changes will be lost.';
function initDraft(p){draft={id:p?.id||null,media:(p?(p.media&&p.media.length?p.media:p.image?[{type:'image',src:p.image}]:[]):[]).map(m=>({type:m.type,src:m.src})),colors:productColors(p).map(c=>({name:c.name,hex:c.hex||parseColor(c.name)})),colorHex:'',colorAuto:true,hsv:[30,.45,.55],sizes:(p?.sizes||[]).map(s=>({size:s.size,qty:s.qty}))}}
const edField=(name,label,control,cls='')=>`<div class="ed-field${cls?' '+cls:''}" data-field="${name}"><label for="f-${name}">${label}</label>${control}<p class="ed-err" id="err-${name}"></p></div>`;
function editorHtml(p){initDraft(p);const v=k=>esc(p?.[k]??''),brand=p?p.brand:productBrand==='All'?'':productBrand,brands=[...new Set([...brandList(),...(brand?[brand]:[])])].sort((a,b)=>a.localeCompare(b)),saved=!!p?.id;
return `<div class="ed"><div class="ed-top"><button type="button" class="ed-back" data-view="products">‹ Products</button><div><p class="ed-kicker">${saved?`Product ${esc(p.id)}`:'New product'}</p><h1>${saved?esc(p.name):p?esc(p.name):'Add product'}</h1></div></div><div class="ed-layout"><form id="productForm" class="ed-main" novalidate>
<section class="ed-sec"><h2>Basics</h2><div class="form-grid">${edField('name','Name',`<input id="f-name" name="name" maxlength="120" value="${v('name')}">`,'full')}${edField('brand','Brand',`<select name="brand" id="brandSelect">${brand?'':'<option value="" selected disabled>Choose a brand</option>'}${brands.map(b=>`<option value="${esc(b)}"${b===brand?' selected':''}>${esc(b)}</option>`).join('')}<option value="${NEW_BRAND}">+ Add a new brand…</option></select><input name="newBrand" id="newBrand" maxlength="60" placeholder="New brand name, e.g. Bottega Veneta" hidden>`)}${edField('category','Gender',`<select id="f-category" name="category">${GENDERS.map(g=>`<option${p?.category===g?' selected':''}>${g}</option>`).join('')}</select>`)}${edField('type','Type <small>sets the store menu and the size chart</small>',`<select id="f-type" name="type">${typeOptions(p?.type||'')}</select>`)}${edField('code','Product code <small>optional</small>',`<input id="f-code" name="code" maxlength="60" value="${v('code')}">`)}</div></section>
<section class="ed-sec"><h2>Price &amp; sale</h2><div class="form-grid">${edField('price','Price (€)',`<input id="f-price" name="price" type="number" min="1" step="1" inputmode="numeric" value="${v('price')}">`)}${edField('discount','Discount (%) <small>optional</small>',`<input id="f-discount" name="discount" type="number" min="0" max="90" step="1" inputmode="numeric" placeholder="0" value="${p?.discount||''}">`)}<p class="ed-hint full" id="salePrice"></p></div></section>
<section class="ed-sec" data-field="sizes"><h2>Sizes &amp; stock</h2><p class="ed-hint">A quantity for every size, on the chart set by the type and gender; customers choose a size on the product page. No sizes = a one-size piece with a single stock number.</p><div class="form-grid">${edField('stock','Stock <small id="stockHint"></small>',`<input name="stock" id="stockInput" type="number" min="0" step="1" inputmode="numeric" value="${p?p.stock??0:0}">`)}</div><div class="size-tools"><span class="size-chart" id="sizeChart"></span><button type="button" id="addPreset"></button><input id="sizeCustom" maxlength="10" aria-label="Other size"><button type="button" id="addSize">Add size</button></div><div class="size-rows" id="sizeRows"></div><div class="size-all" id="sizeAllRow" hidden><label for="sizeAll">Set every size to</label><input id="sizeAll" type="number" min="0" step="1" value="1"><button type="button" id="applyAll">Apply</button></div><p class="color-hint" id="sizeHint" role="status"></p><p class="ed-err" id="err-sizes"></p></section>
<section class="ed-sec" data-field="colors"><h2>Colours</h2><p class="ed-hint">Every colour the piece comes in; customers pick one on the product page. The first is the main colour.</p><div class="color-list" id="colorList"></div><div class="color-row"><span class="color-swatch" id="colorSwatch"></span><input id="colorName" maxlength="60" placeholder="Type a colour (Navy, Ivory, #7A4B2C) or pick one below" autocomplete="off" aria-label="Colour name"><code id="colorHex"></code><button type="button" class="add-color" id="addColor">+ Add colour</button></div><p class="color-hint" id="colorHint" role="status"></p><div class="color-tools"><div class="color-presets">${COLORS.map(([n,h])=>`<button type="button" class="color-chip" data-name="${n}" data-color="${h}" title="${n}" aria-label="${n}" style="--c:${h}"></button>`).join('')}</div><div class="spectrum"><div class="sv" id="sv" role="application" aria-label="Pick a shade"><span class="sv-dot" id="svDot"></span></div><div class="hue" id="hue" aria-label="Pick a hue"><span class="hue-dot" id="hueDot"></span></div></div></div><p class="ed-err" id="err-colors"></p></section>
<section class="ed-sec" data-field="media"><h2>Photos &amp; videos</h2><label class="ed-drop" id="mediaDrop"><input type="file" id="mediaInput" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" multiple hidden><b>Drop photos or videos here, or click to choose</b><span>Photos up to 15 MB, videos up to 95 MB. The first photo is the cover: drag to reorder, or use Make cover.</span></label><p class="ed-err" id="err-media"></p><div class="media-list" id="mediaList"></div></section>
<section class="ed-sec"><h2>Description &amp; details</h2><div class="form-grid">${edField('description','Product description',`<textarea id="f-description" name="description" rows="5" maxlength="4000">${v('description')}</textarea>`,'full')}${edField('composition','Composition',`<textarea id="f-composition" name="composition" rows="4" maxlength="1000" placeholder="Fabric: 90% virgin wool, 10% cashmere&#10;Lining: 100% cotton">${v('composition')}</textarea>`)}${edField('details','Details <small>one per line</small>',`<textarea id="f-details" name="details" rows="4" placeholder="Made in Italy">${esc((p?.details||[]).join('\n'))}</textarea>`)}</div></section>
<section class="ed-sec"><h2>Care</h2><p class="ed-hint">Tick every instruction on the garment label; each shows with its symbol on the product page.</p><div class="care-pick">${CAT.care.map(c=>`<label><input type="checkbox" name="care" value="${c.key}"${p?.care?.includes(c.key)?' checked':''}>${c.svg}<span>${esc(c.title)}</span></label>`).join('')}</div>${edField('careNote','Care notes <small>optional, anything the symbols don’t cover</small>',`<textarea id="f-careNote" name="careNote" rows="3" maxlength="1000" placeholder="Store in the dust bag provided, away from direct sunlight.">${v('careNote')}</textarea>`)}</section>${formError}</form>
<aside class="ed-side"><div class="ed-card ed-vis"><h3>Visibility</h3><label class="ed-radio"><input type="radio" name="visibility" value="published" form="productForm"${p?.hidden?'':' checked'}><span><b>Published</b><small>In the store for customers to see and buy</small></span></label><label class="ed-radio"><input type="radio" name="visibility" value="hidden" form="productForm"${p?.hidden?' checked':''}><span><b>Hidden</b><small>Kept in the CRM only; customers can't see or buy it</small></span></label><label class="ed-check"><input type="checkbox" name="isNew" form="productForm"${p?.isNew?' checked':''}><span><b>New arrival</b><small>Label in the store and a place in the home page's New Arrivals</small></span></label></div><div class="ed-card ed-actions"><button type="submit" form="productForm" class="ed-save" data-save>Save product</button>${saved?`<button type="button" class="ed-ghost" id="duplicateProduct">Duplicate</button>${p.hidden?'<p class="ed-hint">Hidden, so not in the store yet.</p>':`<a class="ed-ghost" href="/#product/${esc(p.id)}" target="_blank" rel="noopener">View in store ↗</a>`}<button type="button" class="ed-danger" id="deleteProduct">Delete product</button>`:''}</div><div class="ed-card"><h3>Preview</h3><div class="pv" id="edPreview"></div><p class="ed-hint">How the piece appears in the store's grids.</p></div></aside></div>
<div class="ed-bar"><span class="ed-state" id="edState" role="status"></span><span class="ed-keys">Ctrl+S saves</span><button type="submit" form="productForm" class="ed-save" data-save>Save product</button></div></div>`}
// Opens the editor for a product, a new product (no id) or a copy; asks first when leaving unsaved changes.
function openProductForm(id,copy){if(current==='editor'&&isDirty()&&!confirm(LEAVE))return;editorSnapshot=null;editorForceDirty=false;editorProduct=copy||(id?store.products.find(p=>p.id===id):null);show('editor');scrollTo(0,0)}
function initEditor(){renderMedia();renderColor();renderColorList();syncSizeChart();renderPreview();editorSnapshot=JSON.stringify(collectProduct());syncDirty()}
// Everything the form holds, as the server expects it (also used to tell whether anything changed).
function collectProduct(){const form=$('#productForm'),fd=new FormData(form),{newBrand,visibility,...fields}=Object.fromEntries(fd),body={...fields,brand:fields.brand===NEW_BRAND?String(newBrand||'').trim():fields.brand||'',hidden:visibility==='hidden',isNew:fd.get('isNew')==='on',care:fd.getAll('care'),media:draft.media.filter(m=>!m.uploading).map(({type,src})=>({type,src})),colors:[...draft.colors],sizes:draft.sizes.map(({size,qty})=>({size,qty})),sizeType:formChart()};
const pending=$('#colorName').value.trim();if(pending&&!body.colors.some(c=>c.name.toLowerCase()===pending.toLowerCase()))body.colors.push({name:pending,hex:draft.colorHex});return body} // a colour typed/picked but not yet added is kept
function isDirty(){if(current!=='editor'||!$('#productForm'))return false;if(editorSnapshot===null)return editorForceDirty;return editorForceDirty||JSON.stringify(collectProduct())!==editorSnapshot}
function setEdState(text,warn=false){const st=$('#edState');if(!st)return;st.textContent=text;$('.ed-bar').classList.toggle('warn',warn)}
function syncDirty(){if(!$('#edState')||editorSnapshot===null&&!editorForceDirty)return;const d=isDirty();setEdState(d?'Unsaved changes':draft.id?'All changes saved':'New product, not saved yet');$('.ed-bar').classList.toggle('dirty',d)}
// The store card as customers will see it, updated while you type.
function renderPreview(){const box=$('#edPreview');if(!box)return;const f=$('#productForm').elements,brand=f.brand.value===NEW_BRAND?f.newBrand.value.trim():f.brand.value,price=+f.price.value||0,disc=Math.min(90,Math.max(0,Math.floor(+f.discount.value)||0)),now=disc?Math.round(price*(100-disc)/100):price,cover=draft.media.find(m=>!m.uploading&&m.type==='image'),hidden=$('[name=visibility][value=hidden]').checked,isNew=$('[name=isNew]').checked;
box.innerHTML=`<div class="pv-img">${cover?`<img src="${esc(cover.src)}" alt="">`:'<span>No photo yet</span>'}${isNew?'<b class="pv-badge">New arrival</b>':''}${hidden?'<b class="pv-hidden">Hidden</b>':''}</div><p class="pv-brand">${esc(brand||'Brand')}</p><p class="pv-name">${esc(f.name.value.trim()||'Product name')}</p><p class="pv-price">${price?disc?`<s>${money(price)}</s> <span>${money(now)}</span> <em>−${disc}%</em>`:money(price):'Price'}</p>`;$('#salePrice').textContent=disc&&price?`Customers pay ${money(now)} instead of ${money(price)}, and find it with the store's "On sale" filter.`:''}
// Checks the fields before saving; each problem is shown under its field and the first one is brought into view.
const ERR_FIELDS={Name:'name',Brand:'brand',Type:'type',Price:'price',Discount:'discount',Stock:'stock','Shoe sizes':'sizes',Size:'sizes',Colour:'colors','Product code':'code',Description:'description',Composition:'composition','Each detail':'details','Care notes':'careNote'};
function fieldError(name,msg){const err=$(`#err-${name}`);if(!err)return false;err.textContent=msg;const box=err.closest('[data-field]');box.classList.toggle('invalid',!!msg);box.querySelectorAll('input:not([type=checkbox]):not([type=radio]):not([type=file]),select,textarea').forEach(i=>i.toggleAttribute('aria-invalid',!!msg));return true}
function validateEditor(){const f=$('#productForm').elements,errs={};document.querySelectorAll('.ed-err').forEach(e=>fieldError(e.id.slice(4),''));
if(!f.name.value.trim())errs.name='Give the product a name.';const brand=f.brand.value;if(!brand)errs.brand='Choose a brand.';else if(brand===NEW_BRAND&&!f.newBrand.value.trim())errs.brand="Type the new brand's name.";
if(!f.type.value)errs.type='Choose a type.';if(!(+f.price.value>=1))errs.price='Enter a price of at least €1.';const d=f.discount.value;if(d!==''&&!(Number.isInteger(+d)&&+d>=0&&+d<=90))errs.discount='A discount is a whole number from 0 to 90.';
if(!draft.sizes.length){const s=f.stock.value;if(s===''||!Number.isInteger(+s)||+s<0)errs.stock='Enter the stock as a whole number, 0 or more.'}
if(draft.media.some(m=>m.uploading))errs.media='Wait until the uploads finish.';else if(!draft.media.some(m=>m.type==='image'))errs.media='Add at least one photo.';
const keys=Object.keys(errs);for(const k of keys)fieldError(k,errs[k]);if(keys.length){const box=$(`#err-${keys[0]}`).closest('[data-field]');box.scrollIntoView({block:'center',behavior:'smooth'});(box.querySelector('input:not([type=file]),select,textarea')||box).focus({preventScroll:true});setEdState(keys.length===1?'1 field needs attention':`${keys.length} fields need attention`,true)}return!keys.length}
async function saveEditor(){if(!$('#productForm')||!validateEditor())return;const btns=[...document.querySelectorAll('[data-save]')];btns.forEach(b=>{b.disabled=true;b.textContent='Saving…'});$('#productForm .form-error').textContent='';setEdState('Saving…');
try{const body=collectProduct(),saved=draft.id?await put('/api/crm/products',{...body,id:draft.id}):await post('/api/crm/products',body);await refresh();const y=scrollY;editorSnapshot=null;editorForceDirty=false;openProductForm(saved.id);scrollTo(0,y);toast('Product saved')}
catch(err){const key=Object.keys(ERR_FIELDS).find(k=>err.message.startsWith(k)),field=/photo/i.test(err.message)?'media':key&&ERR_FIELDS[key];if(!(field&&fieldError(field,err.message)))$('#productForm .form-error').textContent=err.message;setEdState(err.message,true);btns.forEach(b=>{b.disabled=false;b.textContent='Save product'})}}
// Duplicate: a copy of what is on screen, as a new hidden product with the same sizes at 0 stock, ready to adjust and save.
function duplicateProduct(){if(isDirty()&&!confirm('Make a copy of what is on screen? Changes not saved here will only be in the copy.'))return;const b=collectProduct(),copy={...b,name:`${b.name} (copy)`.slice(0,120),code:'',details:String(b.details||'').split(/\r?\n/).filter(Boolean),sizes:b.sizes.map(s=>({size:s.size,qty:0})),stock:0,hidden:true,isNew:false};editorSnapshot=null;editorForceDirty=false;openProductForm(null,copy);editorForceDirty=true;syncDirty();toast('Copy ready (hidden): adjust it, then save')}
// Sizes & stock: one quantity per size; with sizes, the product's stock is their total (worked out here and on the server).
function renderSizes(){draft.sizes=CAT.sortSizes(draft.sizes.map(s=>s.size)).map(n=>draft.sizes.find(s=>s.size===n));$('#sizeRows').innerHTML=draft.sizes.map((s,i)=>`<div class="size-row${s.qty?'':' out'}"><span>${esc(s.size)}</span><button type="button" class="size-step" data-step="-1" data-size-idx="${i}" aria-label="One less in size ${esc(s.size)}">−</button><input type="number" min="0" step="1" value="${s.qty}" data-size-qty="${i}" aria-label="Quantity in size ${esc(s.size)}"><button type="button" class="size-step" data-step="1" data-size-idx="${i}" aria-label="One more in size ${esc(s.size)}">+</button><button type="button" data-drop-size="${i}" aria-label="Remove size ${esc(s.size)}">×</button></div>`).join('')||'<p class="media-empty">No sizes: a one-size piece, using the Stock field.</p>';$('#sizeAllRow').hidden=!draft.sizes.length;syncSizeStock();syncDirty()}
function syncSizeStock(){const stock=$('#stockInput'),has=draft.sizes.length,total=draft.sizes.reduce((sum,s)=>sum+s.qty,0);stock.readOnly=has;if(has)stock.value=total;$('#stockHint').textContent=has?`total of all sizes`:'';const presets=formPresets();$('#addPreset').textContent=`+ Add ${presets[0]}–${presets.at(-1)}`}
// The size chart follows the type (shoes, or clothing for everything else) and gender (Kids). Shoe charts take
// number sizes only, so letter sizes are dropped when the type changes to shoes.
const formChart=()=>{const f=$('#productForm');return CAT.sizeChart(f.type.value,f.category.value)};
const formPresets=()=>CAT.sizePresets(formChart(),$('#productForm').category.value); // quick-add sizes; men's ranges for Men
function syncSizeChart(){const chart=CAT.sizeTypes[formChart()],custom=$('#sizeCustom'),letters=chart.numbers?draft.sizes.filter(s=>!CAT.isNumberSize(s.size)):[];$('#sizeChart').textContent=`Size chart: ${chart.label}${chart.numbers?' · numbers only':''}`;custom.placeholder=chart.numbers?'Other size, e.g. 38.5':'Other size, e.g. XXL, 3Y, 48';custom.inputMode=chart.numbers?'decimal':'text';
if(letters.length)draft.sizes=draft.sizes.filter(s=>!letters.includes(s));$('#sizeHint').textContent=letters.length?`Removed ${letters.map(s=>s.size).join(', ')}: shoes take number sizes only.`:'';renderSizes()}
// Adds sizes to the draft; false when one was refused (a letter size on a shoe chart).
function addSizes(list){const numbers=CAT.sizeTypes[formChart()].numbers;let refused='';for(const size of list){let name=String(size).trim().toUpperCase().replace(/\s+/g,' ');if(numbers)name=name.replace(',','.');if(!name)continue;if(numbers&&!CAT.isNumberSize(name)){refused=name;continue}if(!draft.sizes.some(s=>s.size.toLowerCase()===name.toLowerCase()))draft.sizes.push({size:name,qty:0})}$('#sizeHint').textContent=refused?`"${refused}" isn't a shoe size. Shoes take number sizes only, e.g. 38 or 38.5.`:'';renderSizes();return!refused}
function addCustomSize(){const input=$('#sizeCustom');if(addSizes([input.value]))input.value=''}
// A product's colours (older products have a single `color` / `colorHex`).
const productColors=p=>p?.colors||(p?.color?[{name:p.color,hex:p.colorHex||''}]:[]);
function renderColorList(){$('#colorList').innerHTML=draft.colors.map((c,i)=>`<span class="color-tag${i?'':' main'}"><button type="button" class="color-tag-name" data-edit-color="${i}" title="Edit this colour"><i style="background:${esc(c.hex||'transparent')}"></i>${esc(c.name)}${i?'':' <b>Main</b>'}</button>${i?`<button type="button" data-main-color="${i}" title="Show this colour first" aria-label="Make ${esc(c.name)} the main colour">★</button>`:''}<button type="button" data-drop-color="${i}" aria-label="Remove ${esc(c.name)}">×</button></span>`).join('')||'<p class="media-empty">No colours yet. Type or pick a colour, then press + Add colour.</p>';renderColor()}
function addColor(){const name=$('#colorName').value.trim();if(!name){$('#colorHint').textContent='Type a colour name or pick one from the swatches or the spectrum first.';return}const i=draft.colors.findIndex(c=>c.name.toLowerCase()===name.toLowerCase()),color={name,hex:draft.colorHex};if(i>=0)draft.colors[i]=color;else draft.colors.push(color);$('#colorName').value='';Object.assign(draft,{colorHex:'',colorAuto:true});$('#colorHint').textContent='';renderColorList();$('#colorName').focus()}
// Colour picker: named fashion swatches, a full HSV spectrum (shade square + hue bar), and a live swatch for a typed
// name or hex. A picked shade only renames the colour when the name came from the picker, never a name typed by hand.
const COLORS=[['Black','#111111'],['Charcoal','#3a3a3a'],['Grey','#8c8c8c'],['Light Grey','#cfcfcf'],['Silver','#c0c0c4'],['White','#ffffff'],['Ivory','#f6f1e3'],['Cream','#efe6cf'],['Beige','#d9c7a7'],['Sand','#c9b28c'],['Camel','#b58a5a'],['Tan','#c09a6b'],['Cognac','#9a4f1f'],['Brown','#6b4329'],['Chocolate','#4a2c1d'],['Taupe','#8b7d6b'],['Khaki','#b5a77c'],['Olive','#6b6b3a'],['Green','#2f6b3a'],['Emerald','#1f7a5a'],['Mint','#a8d8c0'],['Teal','#2a7a7a'],['Light Blue','#a9c8e8'],['Blue','#2c5aa0'],['Navy','#1f2a44'],['Lilac','#c8a8d8'],['Purple','#5e3a7a'],['Fuchsia','#c2307a'],['Pink','#e8a0b0'],['Blush','#f0c8c4'],['Coral','#f07c6c'],['Red','#b3261e'],['Burgundy','#6d1a2a'],['Orange','#e07a2e'],['Mustard','#c99a2e'],['Yellow','#e8c547'],['Gold','#c9a24a'],['Rose Gold','#c58b7a']];
const hexToRgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)), rgbToHex=rgb=>'#'+rgb.map(c=>Math.round(c).toString(16).padStart(2,'0')).join('');
const hsvToHex=(h,s,v)=>rgbToHex([5,3,1].map(n=>{const k=(n+h/60)%6;return(v-v*s*Math.max(0,Math.min(k,4-k,1)))*255}));
function hexToHsv(hex){const[r,g,b]=hexToRgb(hex).map(c=>c/255),max=Math.max(r,g,b),d=max-Math.min(r,g,b),h=d?60*(max===r?((g-b)/d+6)%6:max===g?(b-r)/d+2:(r-g)/d+4):0;return[h,max?d/max:0,max]}
const colorCtx=document.createElement('canvas').getContext('2d');
// Colour for a typed name: our fashion names first, then anything the browser understands (lavender, light blue, #7a4b2c, rgb(…)).
function parseColor(text){const t=text.trim();if(!t)return'';const named=COLORS.find(([n])=>n.toLowerCase()===t.toLowerCase());if(named)return named[1];for(const c of new Set([t,t.replace(/\s+/g,'')])){colorCtx.fillStyle='#010203';colorCtx.fillStyle=c;const out=colorCtx.fillStyle;if(/^#[0-9a-f]{6}$/.test(out)&&(out!=='#010203'||c.toLowerCase()==='#010203'))return out}return''}
function nearestColorName(hex){const[r,g,b]=hexToRgb(hex);let best='',dist=Infinity;for(const[n,h]of COLORS){const[r2,g2,b2]=hexToRgb(h),m=(r+r2)/2,d=(2+m/256)*(r-r2)**2+4*(g-g2)**2+(2+(255-m)/256)*(b-b2)**2;if(d<dist){dist=d;best=n}}return best}
function renderColor(){const hex=draft.colorHex,[h,s,v]=draft.hsv;$('#colorSwatch').style.background=hex;$('#colorSwatch').classList.toggle('empty',!hex);$('#colorHex').textContent=hex.toUpperCase();const typed=$('#colorName').value.trim().toLowerCase();$('#addColor').textContent=typed&&draft.colors.some(c=>c.name.toLowerCase()===typed)?'Update colour':'+ Add colour';$('#sv').style.setProperty('--hue',h);Object.assign($('#svDot').style,{left:`${s*100}%`,top:`${(1-v)*100}%`,background:hsvToHex(h,s,v)});$('#hueDot').style.left=`${h/360*100}%`;document.querySelectorAll('.color-chip').forEach(c=>c.classList.toggle('active',c.dataset.color===hex))}
function setColor(hex,name){draft.colorHex=hex;if(hex){const[h,s,v]=hexToHsv(hex);draft.hsv=[s?h:draft.hsv[0],s,v]}if(name!==undefined){$('#colorName').value=name;draft.colorAuto=true}$('#colorHint').textContent='';renderColor()}
function pickFromSpectrum(e){const area=e.currentTarget,r=area.getBoundingClientRect(),x=Math.min(Math.max((e.clientX-r.left)/r.width,0),1),y=Math.min(Math.max((e.clientY-r.top)/r.height,0),1);let[h,s,v]=draft.hsv;if(area.id==='hue'){h=x*360;if(!draft.colorHex){s=Math.max(s,.45);v=Math.max(v,.55)}}else{s=x;v=1-y}const hex=hsvToHex(h,s,v),typed=$('#colorName').value.trim()&&!draft.colorAuto;draft.colorHex=hex;draft.hsv=[h,s,v];if(!typed){$('#colorName').value=nearestColorName(hex);draft.colorAuto=true}$('#colorHint').textContent='';renderColor()}
function renderMedia(){const list=$('#mediaList');if(!list)return;const last=draft.media.length-1,cover=draft.media.findIndex(m=>!m.uploading&&m.type==='image');
list.innerHTML=draft.media.map((m,i)=>m.uploading?`<div class="media-tile uploading" data-upload="${m.id}"><span class="media-name">${esc(m.name)}</span><div class="media-progress"><span style="width:${m.progress}%"></span></div></div>`:`<div class="media-tile" draggable="true" data-index="${i}" title="Drag to reorder">${m.type==='video'?`<video src="${esc(m.src)}#t=0.1" muted playsinline preload="metadata"></video><b class="media-badge">▶ Video</b>`:`<img src="${esc(m.src)}" alt="">`}${i===cover?'<b class="media-cover">Cover</b>':m.type==='image'?`<button type="button" class="media-make-cover" data-cover="${i}">Make cover</button>`:''}<div class="media-tools"><button type="button" data-move="${i}" data-dir="-1" aria-label="Move earlier"${i===0?' disabled':''}>‹</button><button type="button" data-move="${i}" data-dir="1" aria-label="Move later"${i===last?' disabled':''}>›</button><button type="button" data-drop="${i}" aria-label="Remove">×</button></div></div>`).join('')||'<p class="media-empty">No photos yet. Add at least one photo.</p>';renderPreview();syncDirty()}
// Uploads go straight to the server (with progress); the product only references them once saved.
function uploadFile(file){const target=draft,error={set textContent(m){fieldError('media',m)}},kind=file.type.startsWith('video/')?'video':'image';if(file.size>UPLOAD_LIMITS[kind]){error.textContent=`${file.name} is too large: ${kind==='video'?'videos':'photos'} can be up to ${UPLOAD_LIMITS[kind]/MB} MB.`;return}
const item={uploading:true,id:`u${Date.now()}${Math.random().toString(36).slice(2)}`,name:file.name,progress:0};target.media.push(item);renderMedia();
const finish=message=>{if(message){const i=target.media.indexOf(item);if(i>=0)target.media.splice(i,1);error.textContent=message}if(draft===target)renderMedia()};
const xhr=new XMLHttpRequest();xhr.open('POST','/api/crm/uploads');xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');
xhr.upload.onprogress=e=>{if(!e.lengthComputable)return;item.progress=Math.round(e.loaded/e.total*100);const bar=document.querySelector(`[data-upload="${item.id}"] .media-progress span`);if(bar)bar.style.width=`${item.progress}%`};
xhr.onload=()=>{let d={};try{d=JSON.parse(xhr.responseText)}catch{}if(xhr.status<300&&d.src){for(const k in item)delete item[k];Object.assign(item,{type:d.type,src:d.src});finish()}else finish(d.message||`${file.name} could not be uploaded (${xhr.status}).`)};
xhr.onerror=()=>finish(`${file.name} could not be uploaded. Check your connection and the file size.`);xhr.send(file)}
async function deleteProduct(){if(!confirm('Delete this product from the store? This cannot be undone.'))return;try{await api('/api/crm/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draft.id})});editorSnapshot=null;editorForceDirty=false;await refresh();show('products');toast('Product deleted')}catch(err){$('#productForm .form-error').textContent=err.message}}
function leads(){return `${title('Leads')}<div class="table-panel"><div class="table-head"><h3>LEAD PIPELINE</h3><button id="newLead">Add lead</button></div><table class="data-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Source</th><th>Stage</th></tr></thead><tbody>${store.leads.map(l=>`<tr><td>${esc(l.id)}</td><td>${esc(l.name)}</td><td><a class="mail" href="mailto:${esc(l.email)}">${esc(l.email)}</a></td><td>${esc(l.source)}</td><td><select class="status-select ${cls(l.stage)}" data-stage="${esc(l.id)}" aria-label="Stage of ${esc(l.name)}">${(LEAD_STAGES.includes(l.stage)?LEAD_STAGES:[l.stage,...LEAD_STAGES]).map(s=>`<option${s===l.stage?' selected':''}>${esc(s)}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table></div>`}
const LEAD_STAGES=['New','Warm','Qualified','Won','Lost'];
// Discounted price, as the store charges it.
const priceOf=p=>p.discount?Math.round(p.price*(100-p.discount)/100):p.price;
const VIEW_NAMES={dashboard:'Dashboard',orders:'Orders',customers:'Customers',products:'Products',inventory:'Inventory',leads:'Leads',editor:'Product'};
function show(view){if(current==='editor'&&view!=='editor'&&isDirty()&&!confirm(LEAVE))return false;current=view;$('#globalSearch').value='';document.querySelectorAll('.nav-item').forEach(b=>{const on=b.dataset.view===(view==='editor'?'products':view);b.classList.toggle('active',on);b.toggleAttribute('aria-current',on)});document.title=`${VIEW_NAMES[view]} · EA Luxury CRM`;root.innerHTML=view==='editor'?editorHtml(editorProduct):view==='dashboard'?dashboard():view==='orders'?title('Orders')+ordersTable():view==='customers'?customers():view==='products'?products():view==='inventory'?inventory():leads();bindView();if(view==='editor')initEditor();return true}
let modalReturn=null;
function openModal(html,wide=false){modalReturn=document.activeElement;$('#modalBody').innerHTML=html;$('#modalBody h2')?.setAttribute('id','modalTitle');$('.modal-card').classList.toggle('wide',wide);$('#modal').classList.add('open');($('#modalBody input, #modalBody select')||$('#modalClose')).focus()}
function closeModal(){if(!$('#modal').classList.contains('open'))return;$('#modal').classList.remove('open');if(modalReturn?.isConnected)modalReturn.focus()}
const formError='<p class="form-error" role="alert"></p>';
const forms={
 passwordForm:{done:'Password changed',save:async f=>{if(f.next.value!==f.confirm.value)throw new Error('The two new passwords are not the same.');await post('/api/auth/password',{current:f.current.value,next:f.next.value})},html:()=>`<h2>Change password</h2><form id="passwordForm"><label for="pwCurrent">Current password</label><input id="pwCurrent" name="current" type="password" autocomplete="current-password" required><label for="pwNext">New password <small>at least 10 characters</small></label><input id="pwNext" name="next" type="password" autocomplete="new-password" minlength="10" required><label for="pwConfirm">Repeat the new password</label><input id="pwConfirm" name="confirm" type="password" autocomplete="new-password" minlength="10" required>${formError}<button>Change password</button></form>`},
 orderForm:{url:'/api/crm/orders',view:'orders',done:'Order created',html:()=>`<h2>New order</h2><form id="orderForm"><label>Customer</label><select name="customerId" required>${store.customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${esc(c.email)}</option>`).join('')}</select><label>Items</label><input name="items" type="number" min="1" max="99" step="1" value="1" required><label>Total (€)</label><input name="total" type="number" min="1" step="1" required><label>Status</label><select name="status"><option>Processing</option><option>Shipped</option><option>Delivered</option></select>${formError}<button>Create order</button></form>`},
 customerForm:{url:'/api/crm/customers',view:'customers',done:'Customer saved',html:()=>`<h2>Add customer</h2><form id="customerForm"><label>Name</label><input name="name" required maxlength="120"><label>Email</label><input name="email" type="email" required><label>City</label><input name="city" maxlength="80">${formError}<button>Save customer</button></form>`},
 leadForm:{url:'/api/crm/leads',view:'leads',done:'Lead saved',html:()=>`<h2>Add lead</h2><form id="leadForm"><label>Name</label><input name="name" required maxlength="120"><label>Email</label><input name="email" type="email" required><label>Source</label><input name="source" value="Website" maxlength="60">${formError}<button>Save lead</button></form>`},
};
// A [data-view] control can also set the filter the view opens with (data-order-filter / data-stock-filter).
function bindView(){root.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.orderFilter)orderFilter=b.dataset.orderFilter;if(b.dataset.stockFilter)stockFilter=b.dataset.stockFilter;show(b.dataset.view)}));root.querySelectorAll('.chip[data-order-filter]').forEach(b=>b.addEventListener('click',()=>{orderFilter=b.dataset.orderFilter;show('orders')}));root.querySelectorAll('.chip[data-stock-filter]').forEach(b=>b.addEventListener('click',()=>{stockFilter=b.dataset.stockFilter;show('inventory')}));root.querySelectorAll('[data-edit-row]').forEach(r=>r.addEventListener('click',()=>openProductForm(r.dataset.editRow)));$('#newOrder')?.addEventListener('click',()=>openModal(forms.orderForm.html()));$('#newCustomer')?.addEventListener('click',()=>openModal(forms.customerForm.html()));$('#newLead')?.addEventListener('click',()=>openModal(forms.leadForm.html()));$('#newProduct')?.addEventListener('click',()=>openProductForm());$('#brandFilter')?.addEventListener('change',e=>{productBrand=e.target.value;show('products')});$('#productSort')?.addEventListener('change',e=>{productSort=e.target.value;show('products')});root.querySelectorAll('.chip[data-product-filter]').forEach(b=>b.addEventListener('click',()=>{productFilter=b.dataset.productFilter;show('products')}));$('#productSearch')?.addEventListener('input',e=>{productQuery=e.target.value;$('#productGrid').innerHTML=productCardsHtml()});$('#duplicateProduct')?.addEventListener('click',duplicateProduct);root.querySelectorAll('[data-order]').forEach(r=>r.addEventListener('click',e=>{if(e.target.closest('select,a'))return;openModal(orderDetails(store.orders.find(o=>o.id===r.dataset.order)),true)}))}
// Forms are created when the modal opens, so submits are handled by delegation on the modal body.
$('#modalBody').addEventListener('submit',async e=>{const form=forms[e.target.id];if(!form)return;e.preventDefault();const btn=e.submitter||e.target.querySelector('button'),error=e.target.querySelector('.form-error');btn.disabled=true;error.textContent='';try{await(form.save?form.save(e.target):post(form.url,Object.fromEntries(new FormData(e.target))));await refresh();closeModal();show(form.view||current);toast(form.done||'Saved')}catch(err){error.textContent=err.message}finally{btn.disabled=false}});
const onEditor=(type,fn)=>[$('#modalBody'),root].forEach(el=>el.addEventListener(type,fn));
onEditor('change',e=>{if(e.target.id==='brandSelect'){const input=$('#newBrand'),adding=e.target.value===NEW_BRAND;input.hidden=!adding;input.required=adding;if(adding)input.focus();return}if(e.target.id!=='mediaInput')return;fieldError('media','');[...e.target.files].forEach(uploadFile);e.target.value=''});
onEditor('input',e=>{if(e.target.id!=='colorName')return;const text=e.target.value.trim(),hex=parseColor(text);draft.colorAuto=false;draft.colorHex=hex;if(hex){const[h,s,v]=hexToHsv(hex);draft.hsv=[s?h:draft.hsv[0],s,v]}$('#colorHint').textContent=text&&!hex?`"${text}" isn't a colour we recognise. Pick its shade from the swatches or the spectrum; your name is kept.`:'';renderColor()});
onEditor('pointerdown',e=>{const area=e.target.closest('#sv,#hue');if(!area)return;e.preventDefault();area.setPointerCapture(e.pointerId);const move=ev=>pickFromSpectrum({currentTarget:area,clientX:ev.clientX,clientY:ev.clientY});move(e);area.addEventListener('pointermove',move);area.addEventListener('pointerup',()=>area.removeEventListener('pointermove',move),{once:true})});
onEditor('keydown',e=>{if(e.key!=='Enter')return;if(e.target.id==='colorName'){e.preventDefault();addColor()}if(e.target.id==='sizeCustom'){e.preventDefault();addCustomSize()}});
onEditor('input',e=>{if(e.target.form?.id==='productForm'&&(e.target.name==='category'||e.target.name==='type'))syncSizeChart();const q=e.target.closest('[data-size-qty]');if(!q)return;const s=draft.sizes[+q.dataset.sizeQty];s.qty=Math.max(0,Math.floor(+q.value)||0);q.closest('.size-row').classList.toggle('out',!s.qty);syncSizeStock()});
onEditor('click',e=>{const chip=e.target.closest('.color-chip');if(chip)setColor(chip.dataset.color,chip.dataset.name);if(e.target.closest('#addColor'))addColor();
const edit=e.target.closest('[data-edit-color]'),main=e.target.closest('[data-main-color]'),dropColor=e.target.closest('[data-drop-color]');
if(edit){const c=draft.colors[+edit.dataset.editColor];setColor(c.hex||'',c.name);draft.colorAuto=false;$('#colorName').focus()}
if(main){draft.colors.unshift(...draft.colors.splice(+main.dataset.mainColor,1));renderColorList()}
if(dropColor){draft.colors.splice(+dropColor.dataset.dropColor,1);renderColorList()}
const dropSize=e.target.closest('[data-drop-size]');if(e.target.closest('#addPreset'))addSizes(formPresets());if(e.target.closest('#addSize'))addCustomSize();if(dropSize){e.preventDefault();draft.sizes.splice(+dropSize.dataset.dropSize,1);renderSizes()}const move=e.target.closest('[data-move]'),drop=e.target.closest('[data-drop]');if(move){const i=+move.dataset.move,j=i+ +move.dataset.dir;[draft.media[i],draft.media[j]]=[draft.media[j],draft.media[i]];renderMedia()}if(drop){draft.media.splice(+drop.dataset.drop,1);renderMedia()}if(e.target.id==='deleteProduct')deleteProduct()});
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#modalClose').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
// CRM search: every word must match; a result opens the order, the product editor, or the customer / lead list.
$('#globalSearch').addEventListener('input',e=>{if(current==='editor'&&isDirty()&&!confirm(LEAVE)){e.target.value='';return}const words=e.target.value.trim().toLowerCase().split(/\s+/).filter(Boolean);if(!words.length){show(current);return}document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));
const hits=[...store.orders.map(x=>({type:'Order',name:x.id,detail:`${x.customer} · ${money(x.total)} · ${x.status}`,attr:`data-order="${esc(x.id)}"`})),...store.products.map(x=>({type:'Product',name:x.name,detail:`${x.brand}${x.code?` · ${x.code}`:''}`,attr:`data-edit-row="${esc(x.id)}"`})),...store.customers.map(x=>({type:'Customer',name:x.name,detail:`${x.email}${x.city?` · ${x.city}`:''}`,attr:'data-view="customers"'})),...store.leads.map(x=>({type:'Lead',name:x.name,detail:`${x.email} · ${x.stage}`,attr:'data-view="leads"'}))].filter(x=>words.every(w=>`${x.type} ${x.name} ${x.detail}`.toLowerCase().includes(w)));
root.innerHTML=`${title('Search',`${plural(hits.length,'result')} for “${esc(e.target.value.trim())}”`)}<div class="table-panel"><table class="data-table"><tbody>${hits.map(h=>`<tr class="clickable" ${h.attr}><td><span class="status">${h.type}</span></td><td>${esc(h.name)}</td><td>${esc(h.detail)}</td></tr>`).join('')||'<tr><td class="empty-row">Nothing matches. Try a name, an email, an order number or a brand.</td></tr>'}</tbody></table></div>`;bindView()});
// Inline status changes (orders and lead stages) are saved straight away, from the tables or the order details.
async function changeStatus(e){const o=e.target.closest('[data-status]'),l=e.target.closest('[data-stage]'),sel=o||l;if(!sel)return;sel.disabled=true;try{if(o){const u=await put('/api/crm/orders',{id:o.dataset.status,status:o.value});Object.assign(store.orders.find(x=>x.id===u.id),u);toast(`Order ${u.id} is now ${u.status.toLowerCase()}`)}else{const u=await put('/api/crm/leads',{id:l.dataset.stage,stage:l.value});Object.assign(store.leads.find(x=>x.id===u.id),u);toast(`${u.name} moved to ${u.stage}`)}syncBadges()}catch(err){toast(err.message,true)}finally{sel.disabled=false;sel.className=`status-select ${cls(sel.value)}`;if(root.contains(sel)){const y=scrollY;show(current);scrollTo(0,y)}else show(current)}}
root.addEventListener('change',changeStatus);$('#modalBody').addEventListener('change',changeStatus);
$('#alertsBtn').addEventListener('click',()=>{if(store.orders.some(o=>o.status==='Processing')){orderFilter='Processing';show('orders')}else{stockFilter=lowStock().length?'Low stock':'All';show('inventory')}});
$('#changePassword').addEventListener('click',()=>openModal(forms.passwordForm.html()));
$('#signOut').addEventListener('click',async()=>{try{await post('/api/auth/logout',{})}catch{}location.replace('/admin/login.html')});
root.addEventListener('click',e=>{const card=e.target.closest('.product-admin');if(card&&!e.target.closest('.stock-edit')){openProductForm(card.dataset.edit);return}
const step=e.target.closest('[data-step]');if(step){const i=+step.dataset.sizeIdx,s=draft.sizes[i];s.qty=Math.max(0,s.qty+ +step.dataset.step);const row=step.closest('.size-row');row.querySelector('input').value=s.qty;row.classList.toggle('out',!s.qty);syncSizeStock();syncDirty();return}
if(e.target.id==='applyAll'){const n=Math.max(0,Math.floor(+$('#sizeAll').value)||0);draft.sizes.forEach(s=>{s.qty=n});renderSizes();return}
const cover=e.target.closest('[data-cover]');if(cover){const[m]=draft.media.splice(+cover.dataset.cover,1);draft.media.unshift(m);renderMedia()}});
root.addEventListener('input',e=>{if(current!=='editor'||!$('#productForm'))return;const box=e.target.closest('[data-field].invalid');if(box)fieldError(box.dataset.field,'');renderPreview();syncDirty()});
root.addEventListener('change',e=>{if(current==='editor'&&$('#productForm')){renderPreview();syncDirty()}});
root.addEventListener('submit',e=>{if(e.target.id!=='productForm')return;e.preventDefault();saveEditor()});
// Photos: drop files on the drop zone or the photo list; drag tiles to reorder.
const MEDIA_TYPES=/^(image\/(jpeg|png|webp|gif)|video\/(mp4|webm|quicktime))$/;let dragIndex=null;
root.addEventListener('dragstart',e=>{const t=e.target.closest?.('.media-tile[data-index]');if(!t)return;dragIndex=+t.dataset.index;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(dragIndex));t.classList.add('dragging')});
root.addEventListener('dragend',()=>{dragIndex=null;root.querySelectorAll('.dragging,.drop-target').forEach(x=>x.classList.remove('dragging','drop-target'))});
root.addEventListener('dragover',e=>{const zone=e.target.closest?.('#mediaDrop,#mediaList');if(!zone)return;const files=[...e.dataTransfer.types].includes('Files');if(!files&&dragIndex===null)return;e.preventDefault();if(files){$('#mediaDrop').classList.add('over');return}const t=e.target.closest('.media-tile[data-index]');root.querySelectorAll('.drop-target').forEach(x=>{if(x!==t)x.classList.remove('drop-target')});t?.classList.add('drop-target')});
root.addEventListener('dragleave',e=>{if(e.target.id==='mediaDrop')e.target.classList.remove('over')});
root.addEventListener('drop',e=>{const zone=e.target.closest?.('#mediaDrop,#mediaList');if(!zone)return;e.preventDefault();$('#mediaDrop').classList.remove('over');const files=[...e.dataTransfer.files];
if(files.length){const ok=files.filter(f=>MEDIA_TYPES.test(f.type)),bad=files.filter(f=>!MEDIA_TYPES.test(f.type));fieldError('media',bad.length?`${bad.map(f=>f.name).join(', ')}: not a photo or video we can use (JPG, PNG, WebP, GIF, MP4, MOV or WebM).`:'');ok.forEach(uploadFile);return}
const t=e.target.closest('.media-tile[data-index]');if(dragIndex===null||!t)return;const[m]=draft.media.splice(dragIndex,1);draft.media.splice(+t.dataset.index,0,m);dragIndex=null;renderMedia()});
// One-size stock straight from the product list.
root.addEventListener('change',async e=>{const input=e.target.closest('[data-stock]');if(!input)return;const v=Number(input.value);if(!Number.isInteger(v)||v<0){toast('Enter the stock as a whole number, 0 or more.',true);return}input.disabled=true;try{const u=await put('/api/crm/products/stock',{id:input.dataset.stock,stock:v});Object.assign(store.products.find(p=>p.id===u.id),u);syncBadges();toast(`${u.name}: ${u.stock} in stock`);$('#productGrid').innerHTML=productCardsHtml()}catch(err){toast(err.message,true);input.disabled=false}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&current==='editor'&&$('#productForm')){e.preventDefault();saveEditor()}});
addEventListener('beforeunload',e=>{if(isDirty()){e.preventDefault();e.returnValue=''}});
load();
