const $=s=>document.querySelector(s), root=$('#viewRoot');let store={products:[],orders:[],customers:[],leads:[]},current='dashboard';
const money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), cls=v=>String(v??'').replace(/[^A-Za-z]/g,'');
async function api(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
const post=(url,body)=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function refresh(){const [products,orders,customers,leads]=await Promise.all(['/api/products','/api/crm/orders','/api/crm/customers','/api/crm/leads'].map(u=>api(u)));store={products,orders,customers,leads};$('#orderBadge').textContent=orders.length}
async function load(){try{await refresh();show('dashboard')}catch(err){root.innerHTML=`${title('Dashboard')}<div class="empty-state">Could not load CRM data. Is the backend running? (${esc(err.message)})</div>`}}
function title(name,sub='EA LUXURY ITALIAN BRANDS'){return `<div class="page-title"><div><h1>${name}</h1><p>${sub}</p></div><div class="date-chip">${new Date().toLocaleDateString('en-GB',{month:'short',year:'numeric'}).toUpperCase()}</div></div>`}
function dashboard(){const revenue=store.orders.reduce((a,b)=>a+b.total,0);const low=store.products.filter(p=>p.stock<6);const brandTotals={};store.products.forEach(p=>brandTotals[p.brand]=(brandTotals[p.brand]||0)+p.price);const max=Math.max(...Object.values(brandTotals));return `${title('Dashboard','WELCOME TO EA LUXURY ITALIAN BRANDS')}<div class="cards"><div class="metric"><label>TOTAL REVENUE</label><strong>${money(revenue)}</strong><span>↑ Current orders</span></div><div class="metric"><label>CUSTOMERS</label><strong>${store.customers.length}</strong><span>CRM contacts</span></div><div class="metric"><label>ACTIVE ORDERS</label><strong>${store.orders.filter(o=>o.status!=='Delivered').length}</strong><span>Awaiting fulfilment</span></div><div class="metric"><label>LOW-STOCK ITEMS</label><strong>${low.length}</strong><span class="low-stock">Needs attention</span></div></div><div class="dashboard-grid"><div class="panel"><h3>REVENUE OVER TIME</h3><div class="line-chart">${[24,34,29,52,44,63,58,78,66,91].map((h,i)=>`<div class="bar" style="height:${h}%" data-label="${i+1}"></div>`).join('')}</div></div><div class="panel"><h3>SALES BY BRAND</h3>${Object.entries(brandTotals).map(([b,v])=>`<div class="brand-stat"><span>${esc(b)}</span><div class="track"><div class="fill" style="width:${Math.round(v/max*100)}%"></div></div><b>${Math.round(v/max*100)}%</b></div>`).join('')}</div><div class="panel"><h3>CUSTOMER ACTIVITY</h3><div class="activity">${[48,62,35,75,56,83,68,92,61,78].map(h=>`<span style="height:${h}%"></span>`).join('')}</div></div></div>${ordersTable(true)}<div class="table-panel"><div class="table-head"><h3>LOW STOCK ALERTS</h3></div><table class="data-table"><tbody>${low.map(p=>`<tr><td><img class="thumb" src="${esc(p.image)}" alt=""></td><td>${esc(p.name)}<br><small>${esc(p.brand)}</small></td><td class="low-stock">${p.stock} in stock</td></tr>`).join('')||'<tr><td>All products are well stocked.</td></tr>'}</tbody></table></div>`}
function ordersTable(compact=false){const rows=compact?store.orders.slice(0,5):store.orders;return `<div class="table-panel"><div class="table-head"><h3>${compact?'RECENT ORDERS':'ORDERS'}</h3>${compact?'<button data-view="orders">View all →</button>':'<button class="primary" id="newOrder">New order</button>'}</div><table class="data-table"><thead><tr><th>#</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>${rows.map(o=>`<tr class="clickable" data-order="${esc(o.id)}" title="Show order details"><td>${esc(o.id)}</td><td>${esc(o.customer)}</td><td>${o.items}</td><td>${money(o.total)}</td><td><span class="status ${cls(o.status)}">${esc(o.status)}</span></td><td>${esc(o.date)}</td></tr>`).join('')}</tbody></table></div>`}
// Order details: what to ship and where. Orders placed at the store's checkout carry the contact, address and pieces.
function orderDetails(o){const a=o.address,fact=(label,html)=>html?`<div><label>${label}</label><p>${html}</p></div>`:'';
return `<h2>Order ${esc(o.id)}</h2><div class="order-facts">${fact('Customer',[o.customer,o.email,o.phone].filter(Boolean).map(esc).join('<br>'))}${fact('Ship to',a&&[a.line1,a.line2,`${a.postalCode} ${a.city}`,a.country].filter(Boolean).map(esc).join('<br>'))}${fact('Status',`<span class="status ${cls(o.status)}">${esc(o.status)}</span> ${esc(o.date)}${o.source?` · ${esc(o.source)}`:''}`)}${fact('Delivery',esc(o.delivery))}${fact('Payment',esc(o.payment))}${fact('Note',esc(o.note))}</div>
${o.lines?`<table class="data-table order-lines"><thead><tr><th></th><th>Piece</th><th>Colour</th><th>Size</th><th>Qty</th><th>Price</th></tr></thead><tbody>${o.lines.map(l=>`<tr><td><img class="thumb" src="${esc(l.image)}" alt=""></td><td>${esc(l.name)}<br><small>${esc(l.brand)}</small></td><td>${esc(l.color||'–')}</td><td>${esc(l.size||'–')}</td><td>${l.qty}</td><td>${money(l.price*l.qty)}</td></tr>`).join('')}</tbody></table>`:`<p class="media-empty">${o.items} ${o.items===1?'item':'items'}; this order was entered in the CRM, without piece details.</p>`}
<dl class="order-totals">${o.lines?`<dt>Subtotal</dt><dd>${money(o.subtotal)}</dd><dt>Delivery</dt><dd>${o.shipping?money(o.shipping):'Free'}</dd>`:''}<dt>Total</dt><dd>${money(o.total)}</dd></dl>`}
function customers(){return `${title('Customers')}<div class="table-panel"><div class="table-head"><h3>CUSTOMER DIRECTORY</h3><button id="newCustomer">Add customer</button></div><table class="data-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>City</th><th>Orders</th><th>Lifetime spend</th><th>Status</th></tr></thead><tbody>${store.customers.map(c=>`<tr><td>${esc(c.id)}</td><td>${esc(c.name)}</td><td>${esc(c.email)}</td><td>${esc(c.city)}</td><td>${c.orders}</td><td>${money(c.spent)}</td><td><span class="status ${cls(c.status)}">${esc(c.status)}</span></td></tr>`).join('')}</tbody></table></div>`}
const brandList=()=>[...new Set(store.products.map(p=>p.brand))].sort((a,b)=>a.localeCompare(b));
let productBrand='All'; // Products page brand filter
function products(){const brands=brandList();if(!brands.includes(productBrand))productBrand='All';const count=b=>store.products.filter(p=>p.brand===b).length;
return `${title('Products')}<div class="table-panel"><div class="table-head"><h3>PRODUCT CATALOGUE</h3><div class="head-tools"><select id="brandFilter" aria-label="Show brand"><option value="All">All brands (${store.products.length})</option>${brands.map(b=>`<option value="${esc(b)}"${b===productBrand?' selected':''}>${esc(b)} (${count(b)})</option>`).join('')}</select><button class="primary" id="newProduct">Add product</button></div></div></div><div class="products-grid">${store.products.filter(p=>productBrand==='All'||p.brand===productBrand).map(p=>`<article class="product-admin" data-edit="${esc(p.id)}"><img src="${esc(p.image)}" alt="${esc(p.name)}"><div class="meta"><small>${esc(p.brand)}${p.type?` · ${esc(p.type)}`:''}</small>${p.isNew?'<b class="tag">New arrival</b>':''}${p.discount?`<b class="tag sale">−${p.discount}%</b>`:''}<h4>${esc(p.name)}</h4><p>${money(p.price)} · Stock ${p.stock} · ${(p.media||[p.image]).length===1?'1 photo':`${p.media.length} photos/videos`}</p><button class="edit-link">Edit</button></div></article>`).join('')}</div>`}
function inventory(){return `${title('Inventory')}<div class="table-panel"><div class="table-head"><h3>STOCK CONTROL</h3></div><table class="data-table"><thead><tr><th>Item</th><th>Brand</th><th>Gender</th><th>Type</th><th>Price</th><th>Stock</th><th>Stock per size</th></tr></thead><tbody>${store.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.brand)}</td><td>${esc(p.category)}</td><td>${esc(p.type)}</td><td>${money(p.price)}</td><td class="${p.stock<6?'low-stock':''}">${p.stock}</td><td>${(p.sizes||[]).map(s=>`<span class="${s.qty?'':'low-stock'}">${esc(s.size)}: ${s.qty}</span>`).join(' · ')||'One size'}</td></tr>`).join('')}</tbody></table></div>`}
// Product editor: all storefront product-page content (media, Info & Details, care) is entered here.
// Gender is saved as the product's `category`, which the store's Women / Men / Kids pages filter on.
const CAT=window.EA_CATALOG, GENDERS=['Women','Men','Unisex','Kids'], MB=1024*1024, UPLOAD_LIMITS={image:15*MB,video:95*MB}, NEW_BRAND='__new';
let draft=null; // product being edited: {id, media:[{type,src} | {uploading,id,name,progress}]}
// Type dropdown, grouped by what the product is (Clothing, Shoes, …). A product's older type that isn't listed is kept as an option.
function typeOptions(cur){const group=CAT.typeGroup(cur);return `${cur?'':'<option value="" selected disabled>Choose a type</option>'}${cur&&!group?`<option selected>${esc(cur)}</option>`:''}${Object.entries(CAT.types).map(([g,list])=>`<optgroup label="${g}">${(g===group&&!list.includes(cur)?[cur,...list]:list).map(t=>`<option${t===cur?' selected':''}>${esc(t)}</option>`).join('')}</optgroup>`).join('')}`}
function productForm(p){draft={id:p?p.id:null,media:(p?(p.media&&p.media.length?p.media:[{type:'image',src:p.image}]):[]).map(m=>({type:m.type,src:m.src}))};Object.assign(draft,{colors:productColors(p).map(c=>({name:c.name,hex:c.hex||parseColor(c.name)})),colorHex:'',colorAuto:true,hsv:[30,.45,.55],sizes:(p?.sizes||[]).map(s=>({size:s.size,qty:s.qty}))});const v=k=>esc(p?.[k]??''),brands=brandList(),brand=p?p.brand:productBrand==='All'?'':productBrand;
return `<h2>${p?'Edit product':'Add product'}</h2><form id="productForm"><div class="form-grid">
<div class="full"><label>Name</label><input name="name" required maxlength="120" value="${v('name')}"></div>
<div><label>Brand</label><select name="brand" id="brandSelect" required>${brand?'':'<option value="" selected disabled>Choose a brand</option>'}${brands.map(b=>`<option value="${esc(b)}"${b===brand?' selected':''}>${esc(b)}</option>`).join('')}<option value="${NEW_BRAND}">+ Add a new brand…</option></select><input name="newBrand" id="newBrand" maxlength="60" placeholder="New brand name, e.g. Bottega Veneta" hidden></div>
<div><label>Gender</label><select name="category">${GENDERS.map(g=>`<option${p?.category===g?' selected':''}>${g}</option>`).join('')}</select></div>
<div><label>Type <small>decides the menu it appears in and its size chart</small></label><select name="type" required>${typeOptions(p?.type||'')}</select></div>
<div><label>Price (€)</label><input name="price" type="number" min="1" step="1" required value="${v('price')}"></div>
<div><label>Discount (%) <small>optional; shown with the old price crossed out, found with the store's "On sale" filter</small></label><input name="discount" type="number" min="0" max="90" step="1" placeholder="0" value="${p?.discount||''}"></div>
<div><label>Stock <small id="stockHint"></small></label><input name="stock" id="stockInput" type="number" min="0" step="1" required value="${p?p.stock:0}"></div>
<div><label>Product code</label><input name="code" maxlength="60" value="${v('code')}"></div>
<div class="full"><label class="check-row"><input type="checkbox" name="isNew"${p?.isNew?' checked':''}> New arrival <small>shows a "New arrival" label on the product and puts it in the home page's New Arrivals</small></label></div>
<div class="full"><label>Sizes &amp; stock <small>a quantity for every size, on the size chart set by the type and gender; customers choose a size on the product page and filter by size. Leave empty for one-size pieces</small></label><div class="size-tools"><span class="size-chart" id="sizeChart"></span><button type="button" id="addPreset"></button><input id="sizeCustom" maxlength="10" aria-label="Other size"><button type="button" id="addSize">Add size</button></div><div class="size-rows" id="sizeRows"></div><p class="color-hint" id="sizeHint" role="status"></p></div>
<div class="full"><label>Colours <small>every colour this product comes in; customers choose one from a dropdown on the product page (the first is shown first)</small></label><div class="color-list" id="colorList"></div><div class="color-row"><span class="color-swatch" id="colorSwatch"></span><input id="colorName" maxlength="60" placeholder="Type a colour (Navy, Ivory, #7A4B2C) or pick one below" autocomplete="off" aria-label="Colour name"><code id="colorHex"></code><button type="button" class="add-color" id="addColor">+ Add colour</button></div><p class="color-hint" id="colorHint" role="status"></p>
<div class="color-tools"><div class="color-presets">${COLORS.map(([n,h])=>`<button type="button" class="color-chip" data-name="${n}" data-color="${h}" title="${n}" aria-label="${n}" style="--c:${h}"></button>`).join('')}</div><div class="spectrum"><div class="sv" id="sv" role="application" aria-label="Pick a shade"><span class="sv-dot" id="svDot"></span></div><div class="hue" id="hue" aria-label="Pick a hue"><span class="hue-dot" id="hueDot"></span></div></div></div></div>
<div class="full"><label>Photos &amp; videos <small>The first photo is the cover. Photos up to 15 MB, videos up to 95 MB.</small></label><div class="media-list" id="mediaList"></div><label class="upload-btn">+ Add photos or videos<input type="file" id="mediaInput" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,video/quicktime" multiple hidden></label></div>
<div class="full"><label>Product description</label><textarea name="description" rows="5" maxlength="4000">${v('description')}</textarea></div>
<div><label>Composition</label><textarea name="composition" rows="4" maxlength="1000" placeholder="Fabric: 90% virgin wool, 10% cashmere&#10;Lining: 100% cotton">${v('composition')}</textarea></div>
<div><label>Details <small>one per line</small></label><textarea name="details" rows="4" placeholder="Made in Italy">${esc((p?.details||[]).join('\n'))}</textarea></div>
<div class="full"><label>Product care <small>tick every instruction on the garment label, shown with its symbol on the product page</small></label><div class="care-pick">${CAT.care.map(c=>`<label><input type="checkbox" name="care" value="${c.key}"${p?.care?.includes(c.key)?' checked':''}>${c.svg}<span>${esc(c.title)}</span></label>`).join('')}</div></div>
<div class="full"><label>Care notes <small>optional, anything not covered by the symbols</small></label><textarea name="careNote" rows="3" maxlength="1000" placeholder="Store in the dust bag provided, away from direct sunlight.">${v('careNote')}</textarea></div>
</div>${formError}<div class="form-actions"><button type="submit">Save product</button>${p?'<button type="button" class="danger" id="deleteProduct">Delete product</button>':''}</div></form>`}
function openProductForm(id){openModal(productForm(store.products.find(p=>p.id===id)),true);renderMedia();renderColor();renderColorList();syncSizeChart()}
// Sizes & stock: one quantity per size; with sizes, the product's stock is their total (worked out here and on the server).
function renderSizes(){draft.sizes=CAT.sortSizes(draft.sizes.map(s=>s.size)).map(n=>draft.sizes.find(s=>s.size===n));$('#sizeRows').innerHTML=draft.sizes.map((s,i)=>`<div class="size-row${s.qty?'':' out'}"><span>${esc(s.size)}</span><input type="number" min="0" step="1" value="${s.qty}" data-size-qty="${i}" aria-label="Quantity in size ${esc(s.size)}"><button type="button" data-drop-size="${i}" aria-label="Remove size ${esc(s.size)}">×</button></div>`).join('')||'<p class="media-empty">No sizes: this piece is one size, using the Stock field above.</p>';syncSizeStock()}
function syncSizeStock(){const stock=$('#stockInput'),has=draft.sizes.length;stock.readOnly=has;if(has)stock.value=draft.sizes.reduce((sum,s)=>sum+s.qty,0);$('#stockHint').textContent=has?'total of all sizes':'';const presets=formPresets();$('#addPreset').textContent=`+ Add ${presets[0]}–${presets.at(-1)}`}
// The size chart follows the type (shoes, or clothing for everything else) and gender (Kids). Shoe charts take
// number sizes only, so letter sizes are dropped when the type changes to shoes.
const formChart=()=>{const f=$('#productForm');return CAT.sizeChart(f.type.value,f.category.value)};
const formPresets=()=>CAT.sizePresets(formChart(),$('#productForm').category.value); // quick-add sizes; men's ranges for Men
function syncSizeChart(){const chart=CAT.sizeTypes[formChart()],custom=$('#sizeCustom'),letters=chart.numbers?draft.sizes.filter(s=>!CAT.isNumberSize(s.size)):[];$('#sizeChart').textContent=`Size chart: ${chart.label}${chart.numbers?' · numbers only':''}`;custom.placeholder=chart.numbers?'Other size, e.g. 38.5':'Other size, e.g. XXL, 3Y, 48';custom.inputMode=chart.numbers?'decimal':'text';
if(letters.length)draft.sizes=draft.sizes.filter(s=>!letters.includes(s));$('#sizeHint').textContent=letters.length?`Removed ${letters.map(s=>s.size).join(', ')}: shoes take number sizes only.`:'';renderSizes()}
// Adds sizes to the draft; false when one was refused (a letter size on a shoe chart).
function addSizes(list){const numbers=CAT.sizeTypes[formChart()].numbers;let refused='';for(const size of list){let name=String(size).trim().toUpperCase().replace(/\s+/g,' ');if(numbers)name=name.replace(',','.');if(!name)continue;if(numbers&&!CAT.isNumberSize(name)){refused=name;continue}if(!draft.sizes.some(s=>s.size.toLowerCase()===name.toLowerCase()))draft.sizes.push({size:name,qty:0})}$('#sizeHint').textContent=refused?`"${refused}" isn't a shoe size. Shoes take number sizes only, e.g. 38 or 38.5.`:'';renderSizes();return!refused}
function addCustomSize(){const input=$('#sizeCustom');if(addSizes([input.value]))input.value=''}
// A product's colours (older products have a single `color` / `colorHex`).
const productColors=p=>p?.colors||(p?.color?[{name:p.color,hex:p.colorHex||''}]:[]);
function renderColorList(){$('#colorList').innerHTML=draft.colors.map((c,i)=>`<span class="color-tag${i?'':' main'}"><button type="button" class="color-tag-name" data-edit-color="${i}" title="Edit this colour"><i style="background:${esc(c.hex||'transparent')}"></i>${esc(c.name)}${i?'':' <b>Main</b>'}</button>${i?`<button type="button" data-main-color="${i}" title="Show this colour first" aria-label="Make ${esc(c.name)} the main colour">★</button>`:''}<button type="button" data-drop-color="${i}" aria-label="Remove ${esc(c.name)}">×</button></span>`).join('')||'<p class="media-empty">No colours yet. Type or pick a colour, then press + Add colour.</p>';renderColor()}
function addColor(){const name=$('#colorName').value.trim();if(!name){$('#colorHint').textContent='Type a colour name or pick one from the swatches or the spectrum first.';return}const i=draft.colors.findIndex(c=>c.name.toLowerCase()===name.toLowerCase()),color={name,hex:draft.colorHex};if(i>=0)draft.colors[i]=color;else draft.colors.push(color);$('#colorName').value='';Object.assign(draft,{colorHex:'',colorAuto:true});$('#colorHint').textContent='';renderColorList();$('#colorName').focus()}
// Colour picker: named fashion swatches, a full HSV spectrum (shade square + hue bar), and a live swatch for a typed
// name or hex. A picked shade only renames the colour when the name came from the picker, never a name typed by hand.
const COLORS=[['Black','#111111'],['Charcoal','#3a3a3a'],['Grey','#8c8c8c'],['Light Grey','#cfcfcf'],['Silver','#c0c0c4'],['White','#ffffff'],['Ivory','#f6f1e3'],['Cream','#efe6cf'],['Beige','#d9c7a7'],['Sand','#c9b28c'],['Camel','#b58a5a'],['Tan','#c09a6b'],['Cognac','#9a4f1f'],['Brown','#6b4329'],['Chocolate','#4a2c1d'],['Taupe','#8b7d6b'],['Khaki','#b5a77c'],['Olive','#6b6b3a'],['Green','#2f6b3a'],['Emerald','#1f7a5a'],['Mint','#a8d8c0'],['Teal','#2a7a7a'],['Light Blue','#a9c8e8'],['Blue','#2c5aa0'],['Navy','#1f2a44'],['Lilac','#c8a8d8'],['Purple','#5e3a7a'],['Fuchsia','#c2307a'],['Pink','#e8a0b0'],['Blush','#f0c8c4'],['Coral','#f07c6c'],['Red','#b3261e'],['Burgundy','#6d1a2a'],['Orange','#e07a2e'],['Mustard','#c99a2e'],['Yellow','#e8c547'],['Gold','#c9a24a'],['Rose Gold','#c58b7a']];
const hexToRgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)), rgbToHex=rgb=>'#'+rgb.map(c=>Math.round(c).toString(16).padStart(2,'0')).join('');
const hsvToHex=(h,s,v)=>rgbToHex([5,3,1].map(n=>{const k=(n+h/60)%6;return(v-v*s*Math.max(0,Math.min(k,4-k,1)))*255}));
function hexToHsv(hex){const[r,g,b]=hexToRgb(hex).map(c=>c/255),max=Math.max(r,g,b),d=max-Math.min(r,g,b),h=d?60*(max===r?((g-b)/d+6)%6:max===g?(b-r)/d+2:(r-g)/d+4):0;return[h,max?d/max:0,max]}
const colorCtx=document.createElement('canvas').getContext('2d');
// Colour for a typed name: our fashion names first, then anything the browser understands (lavender, light blue, #7a4b2c, rgb(…)).
function parseColor(text){const t=text.trim();if(!t)return'';const named=COLORS.find(([n])=>n.toLowerCase()===t.toLowerCase());if(named)return named[1];for(const c of new Set([t,t.replace(/\s+/g,'')])){colorCtx.fillStyle='#010203';colorCtx.fillStyle=c;const out=colorCtx.fillStyle;if(/^#[0-9a-f]{6}$/.test(out)&&(out!=='#010203'||c.toLowerCase()==='#010203'))return out}return''}
function nearestColorName(hex){const[r,g,b]=hexToRgb(hex);let best='',dist=Infinity;for(const[n,h]of COLORS){const[r2,g2,b2]=hexToRgb(h),m=(r+r2)/2,d=(2+m/256)*(r-r2)**2+4*(g-g2)**2+(2+(255-m)/256)*(b-b2)**2;if(d<dist){dist=d;best=n}}return best}
function renderColor(){const hex=draft.colorHex,[h,s,v]=draft.hsv;$('#colorSwatch').style.background=hex;$('#colorSwatch').classList.toggle('empty',!hex);$('#colorHex').textContent=hex.toUpperCase();const typed=$('#colorName').value.trim().toLowerCase();$('#addColor').textContent=typed&&draft.colors.some(c=>c.name.toLowerCase()===typed)?'Update colour':'+ Add colour';$('#sv').style.setProperty('--hue',h);Object.assign($('#svDot').style,{left:`${s*100}%`,top:`${(1-v)*100}%`,background:hsvToHex(h,s,v)});$('#hueDot').style.left=`${h/360*100}%`;document.querySelectorAll('.color-chip').forEach(c=>c.classList.toggle('active',c.dataset.color===hex))}
function setColor(hex,name){draft.colorHex=hex;if(hex){const[h,s,v]=hexToHsv(hex);draft.hsv=[s?h:draft.hsv[0],s,v]}if(name!==undefined){$('#colorName').value=name;draft.colorAuto=true}$('#colorHint').textContent='';renderColor()}
function pickFromSpectrum(e){const area=e.currentTarget,r=area.getBoundingClientRect(),x=Math.min(Math.max((e.clientX-r.left)/r.width,0),1),y=Math.min(Math.max((e.clientY-r.top)/r.height,0),1);let[h,s,v]=draft.hsv;if(area.id==='hue'){h=x*360;if(!draft.colorHex){s=Math.max(s,.45);v=Math.max(v,.55)}}else{s=x;v=1-y}const hex=hsvToHex(h,s,v),typed=$('#colorName').value.trim()&&!draft.colorAuto;draft.colorHex=hex;draft.hsv=[h,s,v];if(!typed){$('#colorName').value=nearestColorName(hex);draft.colorAuto=true}$('#colorHint').textContent='';renderColor()}
function renderMedia(){const list=$('#mediaList');if(!list)return;const last=draft.media.length-1,cover=draft.media.findIndex(m=>!m.uploading&&m.type==='image');
list.innerHTML=draft.media.map((m,i)=>m.uploading?`<div class="media-tile uploading" data-upload="${m.id}"><span class="media-name">${esc(m.name)}</span><div class="media-progress"><span style="width:${m.progress}%"></span></div></div>`:`<div class="media-tile">${m.type==='video'?`<video src="${esc(m.src)}#t=0.1" muted playsinline preload="metadata"></video><b class="media-badge">▶ Video</b>`:`<img src="${esc(m.src)}" alt="">`}${i===cover?'<b class="media-cover">Cover</b>':''}<div class="media-tools"><button type="button" data-move="${i}" data-dir="-1" aria-label="Move earlier"${i===0?' disabled':''}>‹</button><button type="button" data-move="${i}" data-dir="1" aria-label="Move later"${i===last?' disabled':''}>›</button><button type="button" data-drop="${i}" aria-label="Remove">×</button></div></div>`).join('')||'<p class="media-empty">No photos yet. Add at least one photo.</p>'}
// Uploads go straight to the server (with progress); the product only references them once saved.
function uploadFile(file){const target=draft,error=$('#productForm .form-error'),kind=file.type.startsWith('video/')?'video':'image';if(file.size>UPLOAD_LIMITS[kind]){error.textContent=`${file.name} is too large: ${kind==='video'?'videos':'photos'} can be up to ${UPLOAD_LIMITS[kind]/MB} MB.`;return}
const item={uploading:true,id:`u${Date.now()}${Math.random().toString(36).slice(2)}`,name:file.name,progress:0};target.media.push(item);renderMedia();
const finish=message=>{if(message){const i=target.media.indexOf(item);if(i>=0)target.media.splice(i,1);error.textContent=message}if(draft===target)renderMedia()};
const xhr=new XMLHttpRequest();xhr.open('POST','/api/crm/uploads');xhr.setRequestHeader('Content-Type',file.type||'application/octet-stream');
xhr.upload.onprogress=e=>{if(!e.lengthComputable)return;item.progress=Math.round(e.loaded/e.total*100);const bar=document.querySelector(`[data-upload="${item.id}"] .media-progress span`);if(bar)bar.style.width=`${item.progress}%`};
xhr.onload=()=>{let d={};try{d=JSON.parse(xhr.responseText)}catch{}if(xhr.status<300&&d.src){for(const k in item)delete item[k];Object.assign(item,{type:d.type,src:d.src});finish()}else finish(d.message||`${file.name} could not be uploaded (${xhr.status}).`)};
xhr.onerror=()=>finish(`${file.name} could not be uploaded. Check your connection and the file size.`);xhr.send(file)}
async function saveProduct(form){if(draft.media.some(m=>m.uploading))throw new Error('Please wait until the uploads finish.');const fd=new FormData(form),{newBrand,...fields}=Object.fromEntries(fd),body={...fields,brand:fields.brand===NEW_BRAND?String(newBrand||'').trim():fields.brand,care:fd.getAll('care'),media:draft.media.map(({type,src})=>({type,src})),colors:[...draft.colors],sizes:draft.sizes.map(({size,qty})=>({size,qty})),sizeType:formChart()};
const pending=$('#colorName').value.trim();if(pending&&!body.colors.some(c=>c.name.toLowerCase()===pending.toLowerCase()))body.colors.push({name:pending,hex:draft.colorHex}); // a colour typed/picked but not yet added is kept
if(draft.id)await api('/api/crm/products',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,id:draft.id})});else await post('/api/crm/products',body)}
async function deleteProduct(){if(!confirm('Delete this product from the store? This cannot be undone.'))return;try{await api('/api/crm/products',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:draft.id})});await refresh();closeModal();show('products')}catch(err){$('#productForm .form-error').textContent=err.message}}
function leads(){return `${title('Leads')}<div class="table-panel"><div class="table-head"><h3>LEAD PIPELINE</h3><button id="newLead">Add lead</button></div><table class="data-table"><thead><tr><th>ID</th><th>Name</th><th>Email</th><th>Source</th><th>Stage</th></tr></thead><tbody>${store.leads.map(l=>`<tr><td>${esc(l.id)}</td><td>${esc(l.name)}</td><td>${esc(l.email)}</td><td>${esc(l.source)}</td><td><span class="status ${cls(l.stage)}">${esc(l.stage)}</span></td></tr>`).join('')}</tbody></table></div>`}
function show(view){current=view;$('#globalSearch').value='';document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));root.innerHTML=view==='dashboard'?dashboard():view==='orders'?title('Orders')+ordersTable():view==='customers'?customers():view==='products'?products():view==='inventory'?inventory():leads();bindView()}
function openModal(html,wide=false){$('#modalBody').innerHTML=html;$('.modal-card').classList.toggle('wide',wide);$('#modal').classList.add('open');$('#modalBody input, #modalBody select')?.focus()}function closeModal(){$('#modal').classList.remove('open')}
const formError='<p class="form-error" role="alert"></p>';
const forms={
 orderForm:{url:'/api/crm/orders',view:'orders',html:()=>`<h2>New order</h2><form id="orderForm"><label>Customer</label><select name="customerId" required>${store.customers.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} · ${esc(c.email)}</option>`).join('')}</select><label>Items</label><input name="items" type="number" min="1" max="99" step="1" value="1" required><label>Total (€)</label><input name="total" type="number" min="1" step="1" required><label>Status</label><select name="status"><option>Processing</option><option>Shipped</option><option>Delivered</option></select>${formError}<button>Create order</button></form>`},
 customerForm:{url:'/api/crm/customers',view:'customers',html:()=>`<h2>Add customer</h2><form id="customerForm"><label>Name</label><input name="name" required maxlength="120"><label>Email</label><input name="email" type="email" required><label>City</label><input name="city" maxlength="80">${formError}<button>Save customer</button></form>`},
 leadForm:{url:'/api/crm/leads',view:'leads',html:()=>`<h2>Add lead</h2><form id="leadForm"><label>Name</label><input name="name" required maxlength="120"><label>Email</label><input name="email" type="email" required><label>Source</label><input name="source" value="Website" maxlength="60">${formError}<button>Save lead</button></form>`},
 productForm:{view:'products',save:saveProduct},
};
function bindView(){root.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#newOrder')?.addEventListener('click',()=>openModal(forms.orderForm.html()));$('#newCustomer')?.addEventListener('click',()=>openModal(forms.customerForm.html()));$('#newLead')?.addEventListener('click',()=>openModal(forms.leadForm.html()));$('#newProduct')?.addEventListener('click',()=>openProductForm());$('#brandFilter')?.addEventListener('change',e=>{productBrand=e.target.value;show('products')});root.querySelectorAll('.product-admin').forEach(a=>a.addEventListener('click',()=>openProductForm(a.dataset.edit)));root.querySelectorAll('[data-order]').forEach(r=>r.addEventListener('click',()=>openModal(orderDetails(store.orders.find(o=>o.id===r.dataset.order)),true)))}
// Forms are created when the modal opens, so submits are handled by delegation on the modal body.
$('#modalBody').addEventListener('submit',async e=>{const form=forms[e.target.id];if(!form)return;e.preventDefault();const btn=e.submitter||e.target.querySelector('button'),error=e.target.querySelector('.form-error');btn.disabled=true;error.textContent='';try{await(form.save?form.save(e.target):post(form.url,Object.fromEntries(new FormData(e.target))));await refresh();closeModal();show(form.view)}catch(err){error.textContent=err.message}finally{btn.disabled=false}});
$('#modalBody').addEventListener('change',e=>{if(e.target.id==='brandSelect'){const input=$('#newBrand'),adding=e.target.value===NEW_BRAND;input.hidden=!adding;input.required=adding;if(adding)input.focus();return}if(e.target.id!=='mediaInput')return;$('#productForm .form-error').textContent='';[...e.target.files].forEach(uploadFile);e.target.value=''});
$('#modalBody').addEventListener('input',e=>{if(e.target.id!=='colorName')return;const text=e.target.value.trim(),hex=parseColor(text);draft.colorAuto=false;draft.colorHex=hex;if(hex){const[h,s,v]=hexToHsv(hex);draft.hsv=[s?h:draft.hsv[0],s,v]}$('#colorHint').textContent=text&&!hex?`"${text}" isn't a colour we recognise. Pick its shade from the swatches or the spectrum; your name is kept.`:'';renderColor()});
$('#modalBody').addEventListener('pointerdown',e=>{const area=e.target.closest('#sv,#hue');if(!area)return;e.preventDefault();area.setPointerCapture(e.pointerId);const move=ev=>pickFromSpectrum({currentTarget:area,clientX:ev.clientX,clientY:ev.clientY});move(e);area.addEventListener('pointermove',move);area.addEventListener('pointerup',()=>area.removeEventListener('pointermove',move),{once:true})});
$('#modalBody').addEventListener('keydown',e=>{if(e.key!=='Enter')return;if(e.target.id==='colorName'){e.preventDefault();addColor()}if(e.target.id==='sizeCustom'){e.preventDefault();addCustomSize()}});
$('#modalBody').addEventListener('input',e=>{if(e.target.form?.id==='productForm'&&(e.target.name==='category'||e.target.name==='type'))syncSizeChart();const q=e.target.closest('[data-size-qty]');if(!q)return;const s=draft.sizes[+q.dataset.sizeQty];s.qty=Math.max(0,Math.floor(+q.value)||0);q.closest('.size-row').classList.toggle('out',!s.qty);syncSizeStock()});
$('#modalBody').addEventListener('click',e=>{const chip=e.target.closest('.color-chip');if(chip)setColor(chip.dataset.color,chip.dataset.name);if(e.target.closest('#addColor'))addColor();
const edit=e.target.closest('[data-edit-color]'),main=e.target.closest('[data-main-color]'),dropColor=e.target.closest('[data-drop-color]');
if(edit){const c=draft.colors[+edit.dataset.editColor];setColor(c.hex||'',c.name);draft.colorAuto=false;$('#colorName').focus()}
if(main){draft.colors.unshift(...draft.colors.splice(+main.dataset.mainColor,1));renderColorList()}
if(dropColor){draft.colors.splice(+dropColor.dataset.dropColor,1);renderColorList()}
const dropSize=e.target.closest('[data-drop-size]');if(e.target.closest('#addPreset'))addSizes(formPresets());if(e.target.closest('#addSize'))addCustomSize();if(dropSize){e.preventDefault();draft.sizes.splice(+dropSize.dataset.dropSize,1);renderSizes()}const move=e.target.closest('[data-move]'),drop=e.target.closest('[data-drop]');if(move){const i=+move.dataset.move,j=i+ +move.dataset.dir;[draft.media[i],draft.media[j]]=[draft.media[j],draft.media[i]];renderMedia()}if(drop){draft.media.splice(+drop.dataset.drop,1);renderMedia()}if(e.target.id==='deleteProduct')deleteProduct()});
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#modalClose').addEventListener('click',closeModal);$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();if(!q){show(current);return}document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));const hits=[...store.customers.map(x=>({type:'Customer',name:x.name,detail:x.email})),...store.leads.map(x=>({type:'Lead',name:x.name,detail:x.email})),...store.orders.map(x=>({type:'Order',name:x.id,detail:x.customer})),...store.products.map(x=>({type:'Product',name:x.name,detail:x.brand}))].filter(x=>`${x.name} ${x.detail}`.toLowerCase().includes(q));root.innerHTML=`${title('Search')}<div class="table-panel"><table class="data-table"><tbody>${hits.map(h=>`<tr><td>${h.type}</td><td>${esc(h.name)}</td><td>${esc(h.detail)}</td></tr>`).join('')||'<tr><td>No results</td></tr>'}</tbody></table></div>`});
load();
