const loadCart=()=>{try{const c=JSON.parse(localStorage.getItem('ea-cart')||'[]');return Array.isArray(c)?c:[]}catch{return[]}};
const state={products:[],cart:loadCart(),category:'All',search:''};
// Men/Women collection panel, opened via #men / #women. fromPage: the hash was set by navigating inside the site, so closing can go back.
const coll={category:null,brand:'All',price:'all',sort:'new',fromPage:false};
const COLLECTIONS={'#men':'Men','#women':'Women'}, PRICE_RANGES={all:[0,Infinity],'0-500':[0,500],'500-1000':[500,1000],'1000-':[1000,Infinity]};
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
async function init(){try{const[products,brands]=await Promise.all([json('/api/products'),json('/api/brands')]);state.products=products;$('#brandRow').innerHTML=brands.map(b=>`<button class="brand-pill" data-brand="${esc(b)}">${esc(b)}</button>`).join('')}catch(err){$('#productGrid').innerHTML=`<div class="empty">The collection could not be loaded. Is the backend running? (${esc(err.message)})</div>`;return}renderProducts();renderCart();route()}
const productCard=p=>`<article class="product-card"><div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.brand)} ${esc(p.name)}"></div><div class="product-meta"><div class="product-brand">${esc(p.brand)}</div><h3 class="product-name">${esc(p.name)}</h3><div class="product-row"><span class="product-price">${money(p.price)}</span><button class="add-btn" data-add="${esc(p.id)}">Add to bag</button></div></div></article>`;
function renderProducts(){const q=state.search.toLowerCase();const rows=state.products.filter(p=>(state.category==='All'||p.category===state.category)&&(!q||`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q)));$('#productGrid').innerHTML=rows.length?rows.map(productCard).join(''):'<div class="empty">No pieces found.</div>'}
// "New arrivals" = newest first, where newest is the product added last in products.json.
function renderCollection(){const inCat=state.products.filter(p=>p.category===coll.category);const brands=[...new Set(inCat.map(p=>p.brand))];if(!brands.includes(coll.brand))coll.brand='All';$('#collectionBrands').innerHTML=['All',...brands].map(b=>`<button class="brand-chip${b===coll.brand?' active':''}" data-chip="${esc(b)}">${b==='All'?'All brands':esc(b)}</button>`).join('');const[min,max]=PRICE_RANGES[coll.price];const rows=inCat.filter(p=>(coll.brand==='All'||p.brand===coll.brand)&&p.price>=min&&p.price<max);if(coll.sort==='new')rows.reverse();else rows.sort((a,b)=>coll.sort==='price-asc'?a.price-b.price:b.price-a.price);$('#collectionCount').textContent=`${rows.length} ${rows.length===1?'piece':'pieces'}`;$('#collectionGrid').innerHTML=rows.length?rows.map(productCard).join(''):'<div class="empty">No pieces match these filters.</div>'}
// Brand loader while a collection opens: the EA mark fills from the bottom up (CSS, 1.2s), holds, then fades out.
let loaderTimer;
function showLoader(){const l=$('#loader');clearTimeout(loaderTimer);l.classList.remove('done');l.hidden=false;loaderTimer=setTimeout(()=>{l.classList.add('done');loaderTimer=setTimeout(()=>{l.hidden=true},350)},1500)}
function hideLoader(){clearTimeout(loaderTimer);$('#loader').hidden=true}
function openCollection(category){showLoader();if(coll.category!==category)coll.brand='All';coll.category=category;$('#collectionTitle').textContent=category;renderCollection();$('#collection').hidden=false;$('#collection').scrollTop=0;document.body.classList.add('locked')}
function closeCollection(){hideLoader();$('#collection').hidden=true;document.body.classList.remove('locked')}
function route(){const category=COLLECTIONS[location.hash.toLowerCase()];if(category&&state.products.length)openCollection(category);else closeCollection()}
function saveCart(){localStorage.setItem('ea-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){const count=state.cart.length;const mobile=$('#mobileBagCount');if(mobile)mobile.textContent=count;const items=$('#cartItems');if(!items)return;if(!count){items.innerHTML='<p>Your bag is empty.</p>';$('#cartTotal').textContent=money(0);return}items.innerHTML=state.cart.map((id,i)=>{const p=state.products.find(x=>x.id===id);return p?`<div class="cart-item"><img class="cart-thumb" src="${esc(p.image)}" alt=""><div><h4>${esc(p.name)}</h4><div class="product-brand">${esc(p.brand)}</div><p>${money(p.price)}</p></div><button class="remove" data-remove="${i}" aria-label="Remove ${esc(p.name)}">×</button></div>`:''}).join('');$('#cartTotal').textContent=money(state.cart.reduce((s,id)=>s+(state.products.find(p=>p.id===id)?.price||0),0))}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show')}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){state.cart.push(add.dataset.add);saveCart();openCart()}const rem=e.target.closest('[data-remove]');if(rem){state.cart.splice(+rem.dataset.remove,1);saveCart()}const brand=e.target.closest('[data-brand]');if(brand){state.search=brand.dataset.brand;renderProducts();$('#shop').scrollIntoView()}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.filter;state.search='';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts()}));
['#bagOpen','#mobileBag'].forEach(s=>{const el=$(s);if(el)el.addEventListener('click',openCart)});$('#closeCart').addEventListener('click',closeCart);$('#overlay').addEventListener('click',closeCart);
const openSearch=()=>{$('#searchPanel').classList.add('open');$('#searchInput').focus()};if($('#searchOpen'))$('#searchOpen').addEventListener('click',openSearch);$('#searchClose').addEventListener('click',()=>$('#searchPanel').classList.remove('open'));$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;renderProducts()});
window.addEventListener('hashchange',()=>{coll.fromPage=true;route()});
$('#collectionClose').addEventListener('click',()=>{if(coll.fromPage)history.back();else{history.replaceState(null,'',location.pathname+location.search);closeCollection()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#collection').hidden&&!$('#cartDrawer').classList.contains('open'))$('#collectionClose').click()});
$('#collectionBrands').addEventListener('click',e=>{const chip=e.target.closest('[data-chip]');if(chip){coll.brand=chip.dataset.chip;renderCollection()}});
$('#collectionPrice').addEventListener('change',e=>{coll.price=e.target.value;renderCollection()});
$('#collectionSort').addEventListener('change',e=>{coll.sort=e.target.value;renderCollection()});
$('#newsletterForm').addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.target).get('email');try{const d=await json('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});$('#newsletterMessage').textContent=d.message;e.target.reset()}catch(err){$('#newsletterMessage').textContent=err.message}});
init();
