const loadCart=()=>{try{const c=JSON.parse(localStorage.getItem('ea-cart')||'[]');return Array.isArray(c)?c:[]}catch{return[]}};
const state={products:[],cart:loadCart(),category:'All',search:''};
const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function json(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
async function init(){try{const[products,brands]=await Promise.all([json('/api/products'),json('/api/brands')]);state.products=products;$('#brandRow').innerHTML=brands.map(b=>`<button class="brand-pill" data-brand="${esc(b)}">${esc(b)}</button>`).join('')}catch(err){$('#productGrid').innerHTML=`<div class="empty">The collection could not be loaded. Is the backend running? (${esc(err.message)})</div>`;return}renderProducts();renderCart()}
function renderProducts(){const q=state.search.toLowerCase();const rows=state.products.filter(p=>(state.category==='All'||p.category===state.category)&&(!q||`${p.name} ${p.brand} ${p.category}`.toLowerCase().includes(q)));$('#productGrid').innerHTML=rows.length?rows.map(p=>`<article class="product-card"><div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.brand)} ${esc(p.name)}"></div><div class="product-meta"><div class="product-brand">${esc(p.brand)}</div><h3 class="product-name">${esc(p.name)}</h3><div class="product-row"><span class="product-price">${money(p.price)}</span><button class="add-btn" data-add="${esc(p.id)}">Add to bag</button></div></div></article>`).join(''):'<div class="empty">No pieces found.</div>'}
function saveCart(){localStorage.setItem('ea-cart',JSON.stringify(state.cart));renderCart()}
function renderCart(){const count=state.cart.length;const mobile=$('#mobileBagCount');if(mobile)mobile.textContent=count;const items=$('#cartItems');if(!items)return;if(!count){items.innerHTML='<p>Your bag is empty.</p>';$('#cartTotal').textContent=money(0);return}items.innerHTML=state.cart.map((id,i)=>{const p=state.products.find(x=>x.id===id);return p?`<div class="cart-item"><img class="cart-thumb" src="${esc(p.image)}" alt=""><div><h4>${esc(p.name)}</h4><div class="product-brand">${esc(p.brand)}</div><p>${money(p.price)}</p></div><button class="remove" data-remove="${i}" aria-label="Remove ${esc(p.name)}">×</button></div>`:''}).join('');$('#cartTotal').textContent=money(state.cart.reduce((s,id)=>s+(state.products.find(p=>p.id===id)?.price||0),0))}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')}function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show')}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){state.cart.push(add.dataset.add);saveCart();openCart()}const rem=e.target.closest('[data-remove]');if(rem){state.cart.splice(+rem.dataset.remove,1);saveCart()}const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.category));renderProducts()}const brand=e.target.closest('[data-brand]');if(brand){state.search=brand.dataset.brand;renderProducts();$('#shop').scrollIntoView()}});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.filter;state.search='';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts()}));
['#bagOpen','#mobileBag'].forEach(s=>{const el=$(s);if(el)el.addEventListener('click',openCart)});$('#closeCart').addEventListener('click',closeCart);$('#overlay').addEventListener('click',closeCart);
const openSearch=()=>{$('#searchPanel').classList.add('open');$('#searchInput').focus()};if($('#searchOpen'))$('#searchOpen').addEventListener('click',openSearch);$('#searchClose').addEventListener('click',()=>$('#searchPanel').classList.remove('open'));$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;renderProducts()});
$('#newsletterForm').addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.target).get('email');try{const d=await json('/api/newsletter',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});$('#newsletterMessage').textContent=d.message;e.target.reset()}catch(err){$('#newsletterMessage').textContent=err.message}});
init();
